wsl = true
no-multigrid = false
vsync = true
maximized = false
srgb = false
# idle = 15
neovim-bin = "/usr/bin/nvim"
frame = "full"

[font]
# regular = ["Fira Code Nerd Font"]
# regular = [ "FiraMono Nerd Font" ]
regular = ["FiraMono Nerd Font Mono"]
size = 11.5

# [font.features]
# Fira_Code_Nerd_Font = ["-calt"]

# [font.features]
# FiraMono_Nerd_Font = ["-calt"]

[font.features]
FiraMono\ Nerd\ Font\ Mono\ = ["-calt"]
