return {
  {
    "mason.nvim",
    lazy = true,
    version = "^1.0.0",
    keys = {
      { "<leader>cm", false },
    },
    opts = {
      ensure_installed = {
        -- "bacon",
        "basedpyright",
        "beautysh",
        "black",
        "c3-lsp",
        "cbfmt",
        "clang-format",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "cpplint",
        "csharpier",
        "debugpy",
        "delve",
        "fixjson",
        "gopls",
        "isort",
        "jsonlint",
        --"markdown_oxide",
        -- "mdsf",
        "mdslw",
        "mypy",
        "ocamlformat",
        -- "powershell_es",
        "prettier",
        "ruff",
        "shfmt",
        "sqlfluff",
        "sql-formatter",
        "stylua",
        "ts-standard",
        "vulture",
        "yamlfmt",
        "yamllint",
      },
      --
    },
  },
  { "mason-lspconfig.nvim", version = "^1.0.0", lazy = false },
}
