--########################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mods = require("shared.keymaps.mods")
local progs = require("shared.programs")

--########################

-- Prorams here are mostly utilities
-- that are needed when running in a non-quickshell type env.
-- We do this so we can source the other
-- 'map_programs.conf' file without conflicts in binds.

hl.bind(mods.mod_combos.main_mod_shift .. " + r", hl.dsp.exec_cmd(progs.menu_other))
hl.bind(mods.main_mod .. " + r", hl.dsp.exec_cmd(progs.menu))
hl.bind(mods.main_mod .. " + u", hl.dsp.exec_cmd(progs.locking))
hl.bind(mods.main_mod .. " + m", hl.dsp.exec_cmd(progs.logout_prog))

hl.bind(
  mods.mod_combos.main_mod_ctrl .. " + a",
  hl.dsp.exec_cmd(progs.notifications .. " -t -sw || swaync-client -t -sw")
)
hl.bind(mods.mod_combos.main_mod_shift .. " + s", hl.dsp.exec_cmd(progs.screenshot .. " 'full'"))
hl.bind(mods.mod_combos.main_mod_ctrl .. " + s", hl.dsp.exec_cmd(progs.screenshot .. " 'region'"))

hl.bind(mods.mod_combos.main_mod_ctrl .. " + v", hl.dsp.exec_cmd(progs.clipboard_history))
