#########################
$hyprdir = $HOME/.config/hypr
$rules_dir = $hyprdir/configs/rules
source = $hyprdir/configs/programs.conf
#########################

## This one is global, for per-app, check ghostty rules
windowrule {
  name = no-floating-border
  match:float = true
  border_size = 0
}

source = ./a_generic.conf
source = ./ag_blueman.conf
source = ./ag_mpv.conf
source = ./ag_pip.conf
source = ./ag_popups.conf
source = ./ag_pulse_pavu.conf
source = ./ag_qalculate.conf
source = ./ag_qt5ct.conf
source = ./appimagelauncher.conf
source = ./chromium.conf
source = ./code.conf
source = ./discord.conf
source = ./docker.conf
source = ./ghostty.conf
source = ./jetbrains.conf
source = ./keepassxc.conf
source = ./keymap.conf
source = ./limo.conf
source = ./obsidian.conf
source = ./polychromatic.conf
source = ./qBittorrent.conf
source = ./showmethekey.conf
source = ./signal.conf
source = ./solarar.conf
source = ./spotify.conf
source = ./steam.conf
source = ./swappy.conf
source = ./telegram.conf
source = ./thunar.conf
source = ./viewnoir.conf
source = ./vivaldi.conf
source = ./waypaper.conf
source = ./webapp-manager.conf
source = ./wezterm.conf
source = ./youtube-music_ytm_yt_music.conf
source = ./ytm__pear.conf
source = ./zed-editor.conf
source = ./zen.conf
source = ./zmk-studio.conf
