# Window 55ce1356a9a0 -> AFFiNE-canary:
# 	mapped: 1
# 	hidden: 0
# 	at: 1033,53
# 	size: 3054,1382
# 	workspace: 5 (5)
# 	floating: 0
# 	pseudo: 0
# 	monitor: 0
# 	class: AFFiNE-canary
# 	title: AFFiNE-canary
# 	initialClass: AFFiNE-canary
# 	initialTitle: AFFiNE-canary
# 	pid: 547616
# 	xwayland: 1
# 	pinned: 0
# 	fullscreen: 0
# 	fullscreenClient: 0
# 	overFullscreen: 1
# 	grouped: 0
# 	tags:
# 	swallowing: 0
# 	focusHistoryID: 0
# 	inhibitingIdle: 0
# 	xdgTag:
# 	xdgDescription:
# 	contentType: none
#

# Tagging
windowrule {
  name = tag-affine
  match:class = ^(AFFiNE.*)$
  match:initial_class = ^(AFFiNE.*)$ 
  match:title = ^(AFFiNE.*)$
  match:initial_title = ^(AFFiNE.*)$
  tag = +affine
}

# Effects

## Generic opacity for tagged things
windowrule {
  name = tagged-affine
  match:tag = affine
  opacity = 1.0 override 1.0 override
  persistent_size = true
}

## Float things
windowrule {
  name = workspace-affine
  float = false
  workspace = 5 silent
  persistent_size = true

  # no_initial_focus = true
  # float = true
  # center = true
  # size = X_POS Y_POS
}

