windowrule {
  name = float-media-players
  match:title = ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
  float = true
  size = 960 540
  move = 25%-
}

# windowrule = float,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
# windowrule = size 960 540,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
# windowrule = move 25%-,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
