windowrule {
  name = float-pip-librewolf
  match:class = ^()$
  match:title = ^(Picture-in-Picture)$
  float = true
}

windowrule {
  name = non-initial-focus-pip-librewolf
  match:title = ^(Picture-in-Picture):workspace$
  no_initial_focus = true
}

windowrule {
  name = float-pip-librewolf
  match:class = ^(LibreWolf)$
  match:title = ^(Picture-in-Picture)$
  float = true
}

# windowrule = float,class:^()$,title:^(Picture in picture)$"
# windowrule = noinitialfocus,title:^(Picture-in-Picture):workspace
# windowrule = float,class:^(LibreWolf)$,title:^(Picture-in-Picture)$
