windowrule {
  name = float-qalculate
  match:class = ^(io.github.Qalculate.qalculate-qt)$
  float = true
  center = true
  size = 600 900
}

# windowrule = float,class:^(io.github.Qalculate.qalculate-qt)$
# windowrule = size 600 900,class:^(io.github.Qalculate.qalculate-qt)$
# windowrule = stayfocused,class:^(io.github.Qalculate.qalculate-qt)$,title:^(Qalculate!)$
