#### Actual AlecaFrame window info for matching
# Window 55c032deb3e0 -> AlecaFrame:
# 	mapped: 1
# 	hidden: 0
#
# 	at: 53,110
#
# 	size: 1920,1080
#
# 	workspace: 4 (4)
# 	floating: 1
# 	pseudo: 0
# 	monitor: 0
#
# 	class: overwolf.exe
# 	title: AlecaFrame
# 	initialClass: overwolf.exe
# 	initialTitle: AlecaFrame
#
# 	pid: 1267765
# 	xwayland: 0
# 	pinned: 0
# 	fullscreen: 0
# 	fullscreenClient: 0
# 	grouped: 0
# 	tags:
# 	swallowing: 0
# 	focusHistoryID: 0
# 	inhibitingIdle: 0
# 	xdgTag: proton-game
# 	xdgDescription: A game running through proton
# 	contentType: game


#### This is the little command window that pops up that then calls the actual AlecaFrame
# Window 55c032e82880 -> :
# 	mapped: 1
# 	hidden: 0
# 	at: 2477,694
# 	size: 166,52
# 	workspace: 4 (4)
# 	floating: 1
# 	pseudo: 0
# 	monitor: 0
#
# 	class: explorer.exe
# 	title:
# 	initialClass: explorer.exe
# 	initialTitle:
#
# 	pid: 1294287
# 	xwayland: 0
# 	pinned: 0
# 	fullscreen: 0
# 	fullscreenClient: 0
# 	grouped: 0
# 	tags:
# 	swallowing: 0
# 	focusHistoryID: 0
# 	inhibitingIdle: 0
# 	xdgTag: proton-game
# 	xdgDescription: A game running through proton
# 	contentType: game


#### The (non-rendering) Overwolf Quick Launcher window
# Window 55c032e02ce0 -> Overwolf Quick Launcher:
# 	mapped: 1
# 	hidden: 0
# 	at: 5,53
# 	size: 1014,1382
# 	workspace: 4 (4)
# 	floating: 0
# 	pseudo: 0
# 	monitor: 0
#
# 	class: overwolf.exe
# 	title: Overwolf Quick Launcher
# 	initialClass: overwolf.exe
# 	initialTitle: Overwolf Quick Launcher
#
# 	pid: 1304326
# 	xwayland: 0
# 	pinned: 0
# 	fullscreen: 0
# 	fullscreenClient: 0
# 	grouped: 0
# 	tags:
# 	swallowing: 0
# 	focusHistoryID: 0
# 	inhibitingIdle: 0
# 	xdgTag: proton-game
# 	xdgDescription: A game running through proton
# 	contentType: game


# Tagging Overwolf Quick Launcher
windowrule {
  name = tag-overwolf-quick-launcher
  match:class = ^(overwolf.exe)$
  match:title = ^(Overwolf Quick Launcher)$
	match:initial_class = ^(overwolf.exe)$
	match:initial_title = ^(Overwolf Quick Launcher)$
  tag = +overwolf-overwolf-quick-launcher
}

# Tagging little window
windowrule {
  name = tag-overwolf-spawn-window
  match:class = ^(explorer.exe)$
  match:title = ^()$
	match:initial_class = ^(explorer.exe)$
	match:initial_title = ^()$
  tag = +overwolf-spawn-window
}

# Tagging AlecaFrame
windowrule {
  name = tag-alecaframe
  match:class = ^(overwolf.exe)$
  match:title = ^(AlecaFrame)$
	match:initial_class = ^(overwolf.exe)$
	match:initial_title = ^(AlecaFrame)$
  tag = +overwolf-alecaframe
}

# Effects

## Overwolf Quick Launcher
windowrule {
  name = tagged-overwolf-quick-launcher
  match:tag = overwolf-overwolf-quick-launcher
  workspace = 8 silent
  opacity = 1.0 override 1.0 override
  # maximize = true
  # border_size = 0
  # persistent_size = true

  # float = true
  # center = true
  # size = 1280 720
}

## Little spawn window
windowrule {
  name = tagged-overwolf-spawn-window
  match:tag = overwolf-spawn-window
  workspace = 8 silent
  opacity = 1.0 override 1.0 override
  # maximize = true
  # border_size = 0
  # persistent_size = true

  # float = true
  # center = true
  # size = 1280 720
}

## AlecaFrame
windowrule {
  name = tagged-overwolf-alecaframe-force-workspace
  match:tag = overwolf-alecaframe
  workspace = 8 silent
  opacity = 1.0 override 1.0 override
  maximize = true
  # border_size = 0
  # persistent_size = true

  # float = true
  # center = true
  # size = 1280 720
}

