# class: vivaldi-ndmlnoabbeafemnnijijgjkohaffjjnm-Default
# title: Calendly - Scheduling - Event types - Scheduling - Calendly
# initialClass: vivaldi-ndmlnoabbeafemnnijijgjkohaffjjnm-Default
# initialTitle: Calendly - Scheduling


# Tagging
windowrule {
  name = tag-vivaldi-calendly
  match:class = ^(vivaldi-.*-[dD]efault)$
  match:initial_class = ^(vivaldi-.*-[dD]efault)$ 
  match:title = ^([cC]alendly.*)$
  match:initial_title = ^([cC]alendly.*)$
  tag = +vivaldi_calendly
}

# Effects

## Float things
windowrule {
  name = float-tagged-vivaldi-calendly
  match:class = ^(vivaldi-.*-[dD]efault)$
  match:tag = vivaldi_calendly
  float = true
  center = true
  size = 1105 1150
}
