


## Dev tools
windowrule = float,class:^(Chromium)$,initial-title:^(Devtools)$"
windowrule = persistentsize,class:^(Chromium)$,initial-title:^(Devtools)$"
windowrule = size 2030 1060,class:^(Chromium)$,initial-title:^(Devtools)$"



# windowrule = opacity 1.0 override 1.0 override,class:^([cC]hromium)$
windowrule = pseudo,class:^([cC]hromium)$
windowrule = size 2660 1300,class:^([cC]hromium)$
windowrule = persistentsize,class:^([cC]hromium)$ 
# allows spawning it via mod + b, without swapping
# windowrule = noinitialfocus,class:^([cC]hromium)$, # allows spawning it via mod + b, without swapping
