# class: DaVinci Control Panels Setup
# title: DaVinci Control Panels Setup
# initialClass: DaVinci Control Panels Setup
# initialTitle: DaVinci Control Panels Setup


# Tagging
windowrule {
  name = tag-davinici-panels
  match:class = ^(DaVinci Control Panels Setup)$
  match:initial_class = ^(DaVinci Control Panels Setup)$ 
  match:title = ^(DaVinci Control Panels Setup)$
  match:initial_title = ^(DaVinci Control Panels Setup)$
  tag = +daviniciPanels
}

# Effects

## Generic opacity for tagged things
windowrule {
  name = tagged-davinici-panels
  match:tag = daviniciPanels
  opacity = 1.0 override 1.0 override
}

## Float things
windowrule {
  name = float-tagged-davinici-panels
  match:tag = daviniciPanels
  # workspace = N silent
  float = true
  center = true
  size = 1280 720
  # opacity = 1.0 override 1.0 override
}


## Other options/effects
# border_size = 0
