# Tagging
windowrule {
  name = tag-discordForksClass
  match:class = ^([dD]iscord|[aA]rmcord|[wW]ebcord|[vV]encord|[vV]esktop)$
  tag = +discordForksClass
}

windowrule {
  name = style-discordForksClass
  match:tag = discordForksClass
  opacity = 1.00
  workspace = 9 silent
  maximize = true
  # border_size = 0
}

# Tagging
windowrule {
  name = tag-discordForksInitialClass
  match:initial_class = ^([dD]iscord|[aA]rmcord|[wW]ebcord|[vV]encord|[vV]esktop)$
  tag = +discordForksInitialClass
}

## Discord (and forks)


## windowrule = tag +discordForksInitialClass,initialClass:^([dD]iscord|[aA]rmcord|[wW]ebcord|[vV]encord|[vV]esktop)$
## # windowrule = size 100% 100%,tag:discordForksInitialClass
## 
## windowrule = tag +discordForks,class:^([dD]iscord|[aA]rmcord|[wW]ebcord|[vV]encord|[vV]esktop)$
## windowrule = opacity 1.00,tag:discordForks
## windowrule = workspace 7 silent,tag:discordForks
## 
## # It would seem that I cannot hook (for maximize) the 
## # window if we're using noinitialfocus... Hmmm... 
## #
## # windowrule = noinitialfocus,tag:discordForksInitialClass
## 
## # Vesktop has a special setting to make the title static and always 
## # be 'Vesktop'. Turn it on.
## windowrule = maximize,tag:discordForks
## 
## 
## # windowrule = maximize,tag:discordForks
## # windowrule = fullscreenstate 2 2,tag:discordForks
## # windowrule = persistentsize,tag:discordForks
## # windowrule = float,class:^(discord|armcord|webcord|vencord|vesktop)$
