
## Discord (and forks)
windowrule = tag +discordand,class:^(discord|armcord|webcord|vencord|vesktop)$
windowrule = workspace 7,tag:discordand
windowrule = noinitialfocus,tag:discordand
# class:^(discord|armcord|webcord|vencord|vesktop)$
windowrule = opacity 1.00,tag:discordand
# class:^(discord|armcord|webcord|vencord|vesktop)$
# windowrule = float,class:^(discord|armcord|webcord|vencord|vesktop)$
windowrule = persistentsize,tag:discordand
# class:^(discord|armcord|webcord|vencord|vesktop)$
#

