windowrule {
  name = workspace-docker-desktop
  match:class = ^(Docker Desktop)$
  workspace = 8 silent
  no_initial_focus = true
}

# class: Docker Desktop
# title: Images - Docker Desktop
# initialClass: Docker Desktop
# initialTitle: Docker Desktop

# windowrule = workspace 8,class:^(Docker Desktop)$
