windowrule {
  name = tag-ghostty
  match:class = ^(com\.mitchellh\.ghostty)$
  tag = +ghostty
}

windowrule {
  name = float-tagged-ghostty
  match:tag = ghostty
  float = true
  center = true
  size = 2000 1330
  persistent_size = true
  pseudo = true
  opaque = true
  # border_size = 0
}

## Only when floating, have no border
windowrule {
  name = float-tagged-no-border
  match:tag = ghostty
  match:float = true
  border_size = 0
}

# Ghostty

# class: com.mitchellh.ghostty
# title: Ghostty
# initialClass: com.mitchellh.ghostty
# initialTitle: Ghostty
# at: 1302,175
# size: 2517,1139

## windowrule = tag +ghostty,class:^(com\.mitchellh\.ghostty)$
## # windowrule = float,tag:ghostty
## # windowrule = size 2600 1200,tag:ghostty
## windowrule = pseudo,tag:ghostty
## windowrule = center, float, size 2000 1330,tag:ghostty
## windowrule = persistentsize,tag:ghostty
## 
## # windowrule = nodim, opaque, tag:ghostty
## windowrule = opaque, tag:ghostty

# windowrule = forcergbx,tag:ghostty
# windowrule = dimaround, tag:ghostty
# size: 3726,1382
# windowrule = maxsize 3800 1400,tag:ghostty

# windowrule = size 2083 1134, class:^com\.mitchellh\.ghostty$
# windowrule = opacity 0.8 0.8, tag:ghostty
# windowrule = noblur, tag:ghostty
# windowrule = noblur,class:^()$
