windowrule {
  name = float-keepass
  match:class = ^(org.keepassxc.KeePassXC)$
  float = true
  center = true
  size = 1450 1000
}

# keepass pass keyring


# windowrule = float,class:^(org.keepassxc.KeePassXC)$
# windowrule = size 1450 1000,class:^(org.keepassxc.KeePassXC)$
