windowrule {
  name = float-keymapp
  match:class = ^(keymapp)$
  float = true
  center = true
  size = 1450 1000
}

# windowrule = float,class:^(keymapp)$
# windowrule = size 1450 1000,class:^(keymapp)$
