# class: kitty
# title: ~
# initialClass: kitty
# initialTitle: kitty
# Tagging

windowrule {
  name = tag-kitty
  match:class = ^(kitty)$
  match:initial_class = ^(kitty)$ 
  match:initial_title = ^(kitty)$
  tag = +kitty
}

# Effects

## Float things
windowrule {
  name = float-tagged-kitty
  match:tag = kitty
  float = true
  center = true
  size = 1280 720
}

windowrule {
  name = float-tagged-no-border
  match:tag = kitty
  match:float = true
  border_size = 0
}
