windowrule {
  name = float-limo
  match:class = ^(limo)$
  match:initial_class = ^(limo)$
  float = true
  center = true
  size = 800 600
  # opacity = 1.0 override 1.0 override
}

windowrule {
  name = float-limo-install-mod
  match:class = ^(limo)$
  match:title = ^(Install Mod)$
  float = true
  center = true
  size = 800 600
  # opacity = 1.0 override 1.0 override
}

# class: limo
# title: Install Mod
# initialClass: limo
# initialTitle: Install Mod

# windowrule = float,class:^(limo)$,title:^(Install Mod)$
# windowrule = size 800 600,class:^(limo)$,title:^(Install Mod)$
# windowrule = center,class:^(limo)$,title:^(Install Mod)$
#
# windowrule = float,class:^(limo)$,initialClass:^(limo)$
