
## Obsidian
windowrule = workspace 5 silent,class:^([oO]bsidian)$
# windowrule = float,class:^([oO]bsidian)$
windowrule = persistentsize,class:^([oO]bsidian)$
# windowrule = noinitialfocus,class:^([oO]bsidian)$ # allows spawning without swapping to it
