windowrule {
  name = workspace-obsidian
  match:class = ^([oO]bsidian)$
  float = false
  workspace = 5 silent
  persistent_size = true
}


# Starting mini-window
windowrule {
  name = mini-window-obsidian
  match:class = ^([oO]bsidian)$
  match:title = ^([oO]bsidian)$
  float = true
  persistent_size = true
}

## mini window
# class: obsidian
# title: Obsidian
# initialClass: obsidian
# initialTitle: Obsidian

## Obsidian

# windowrule = workspace 5 silent,class:^([oO]bsidian)$
# # windowrule = float,class:^([oO]bsidian)$
# windowrule = persistentsize,class:^([oO]bsidian)$
# windowrule = noinitialfocus,class:^([oO]bsidian)$ # allows spawning without swapping to it
