
# class: polychromatic
# title: Device Information - Razer Viper V2 Pro (Wired)
# initialClass: polychromatic
# initialTitle: Device Information - Razer Viper V2 Pro (Wired)

# Razer / mouse / polychromatic
windowrule = tag +polychromatic,class:^polychromatic$
windowrule = float,tag:polychromatic
windowrule = size 1050 950,tag:polychromatic
# windowrule = size 200 400, class:^polychromatic$, initial-title:^Device Information - .+$
