windowrule {
  name = float-qBittorrent-torrent
  match:class = ^(org.qbittorrent.qBittorrent)$
  tag = +torrent
}

windowrule {
  name = float-qBittorrent-torrent-window
  match:tag = torrent
  match:initial_title = ^[(^qBittorrent v.*)]$
  float = true
  persistent_size = true
}

# windowrule = tag +torrent,class:^org.qbittorrent.qBittorrent$
# windowrule = float, tag:torrent,initial-title:^[(^qBittorrent v.*)]$
# windowrule = persistentsize,tag:torrent
