
## Signal messenger
windowrule = workspace 6,class:^([sS]ignal)$
windowrule = float,class:^([sS]ignal)$
windowrule = center,class:^([sS]ignal)$
windowrule = persistentsize,class:^([sS]ignal)$
windowrule = noinitialfocus,class:^([sS]ignal)$, # allows spawning without swapping to it
