windowrule {
  name = workspace-signal 
  match:class = ^([sS]ignal)$
  workspace = 6 silent
  float = true
  center = true
  size = 1600 1250
  persistent_size = true
}

# Signal messenger

# windowrule = workspace 6 silent,class:^([sS]ignal)$
# windowrule = float,class:^([sS]ignal)$
# windowrule = center,class:^([sS]ignal)$
# windowrule = persistentsize,class:^([sS]ignal)$
# windowrule = noinitialfocus,class:^([sS]ignal)$, # allows spawning without swapping to it
