windowrule {
  name = float-solaar
  match:class = ^(solaar)$
  match:title = ^(Solaar)$
  float = true
  center = true
  size = 1000 650
}

windowrule {
  name = float-solaar-rule-editor
  match:class = ^(solaar)$
  match:title = ^(Solaar Rule Editor)$
  float = true
  center = true
  size = 600 500
}


# Logitech logi controller
# windowrule = float,class:^(solaar)$
# windowrule = size 1000 650,class:^(solaar)$,title:^(Solaar)$
# windowrule = size 600 500,class:^(solaar)$,title:^(Solaar Rule Editor)$
