#############
### Steam ###
#############

windowrule = workspace 4,class:^([sS]team)$

windowrule = tag +steamUpdater,title:^(Steam - Self Updater)$
windowrule = float,class:^()$,tag:steamUpdater
windowrule = noinitialfocus,tag:steamUpdater
# title:^(Steam - Self Updater)$

# class: steam
# title: Sign in to Steam
# initialClass: steam
# initialTitle: Sign in to Steam
windowrule = noinitialfocus,class:^([sS]team)$,title:^(Sign in to [sS]team)$


windowrule = opacity 1.0 override 1.0,class:^([sS]team)$,title:^([sS]team)$
# windowrule = float,title:^([sS]team)$
# windowrule = float,class:^([sS]team)$

windowrule = size 2400 1250,title:^([sS]team)$  #class:^([sS]team)$

windowrule = opacity 1.0 override 1.0,class:^([sS]team)$,title:^([sS]team [sS]ettings)$
windowrule = float,title:^([sS]team [sS]ettings)$,
windowrule = size 850 720,title:^([sS]team [sS]ettings)$

windowrule = center,title:^([sS]ign in to [sS]team)$
windowrule = size 850 720,title:^([sS]ign in to [sS]team)$

# TODO: need to pin the friends list as well


# windowrule = tag +steamClass,class:^([sS]team)$
# windowrule = workspace 4,tag:steamClass
# windowrule = stayfocused,tag:steamClass
#
# windowrule = tag +steamTitle,title:^[sS]team.-.[sS].*$
# # windowrule = tag +steamTitle,title:^[sS]team(\s?|.?)?(.-.[sS])?.*$
# windowrule = stayfocused,tag:steamTitle
#
# # class:^([sS]team)$
#
# windowrule = float,class:^()$,tag:steamTitle
# # title:^(Steam - Self Updater)$
#
# windowrule = opacity 1.0 override 1.0,tag:steamClass
# # class:^([sS]team)$,title:^([sS]team)$
# # windowrule = float,title:^([sS]team)$
# # windowrule = float,class:^([sS]team)$
#
# windowrule = size 2400 1250,title:^([sS]team)$  #class:^([sS]team)$
#
# windowrule = opacity 1.0 override 1.0,tag:steamTitle
# # ,class:^([sS]team)$,title:^([sS]team [sS]ettings)$
# windowrule = float,title:^([sS]team [sS]ettings)$,
# windowrule = size 850 720,title:^([sS]team [sS]ettings)$
#
# windowrule = center,title:^([sS]ign in to [sS]team)$
# windowrule = size 850 720,title:^([sS]ign in to [sS]team)$


#################
### Steam END ###
#################
