
windowrule = opacity 1.00,class:^(QQ|Telegram)$


## Telegram
windowrule = workspace 6,class:^(org.telegram.desktop)$
# windowrule = float,class:^(org.telegram.desktop)$
windowrule = center,class:^(org.telegram.desktop)$
windowrule = persistentsize,class:^(org.telegram.desktop)$
windowrule = noinitialfocus,class:^(org.telegram.desktop)$, # allows spawning without swapping to it
