windowrule {
  name = float-thunar
  match:class = ^([tT]hunar|nemo|dolphin)$
  float = true
  center = true
  size = 1450 1000
  # opacity = 1.0 override 1.0 override
}

# Thunar / thunar / nemo / dolphin file managers


## windowrule = float,class:^([tT]hunar|nemo|dolphin)$
## windowrule = size 1450 1000,title:^([tT]hunar)$
