windowrule {
  name = float-viewnior
  match:class = ^([vV]iewnior)$
  float = true
  center = true
  size = 2560 1200
  # opacity = 1.0 override 1.0 override
}

# windowrule = float,class:^(viewnior)$
# windowrule = size 2560 1200,class:^(viewnior)$
