# Tagging
windowrule {
  name = tag-vivaldi-init-class
  match:initial_class = ^([vV]ivaldi)(-+)(stable?)$
  tag = +vbrowserInitClass
}

# Tagging
windowrule {
  name = tag-vivaldi-init-title
  match:initial_title = ^([vV]ivaldi(\s+)(-)(\s+)[vV]ivaldi)$
  tag = +vbrowserInitTitle
}

windowrule {
  name = workspace-tagged-vivaldi
  match:tag = vbrowserInitTitle
  workspace = 1 silent
}

windowrule {
  name = workspace-tagged-vivaldi
  match:tag = vbrowserInitClass
  workspace = 1 silent
}

windowrule {
  name = opacity-tagged-vivaldi
  match:tag = vbrowserInitClass
  opacity = 1.0 override 1.0 override
  opaque = true
}

windowrule {
  name = opacity-tagged-vivaldi
  match:tag = vbrowserInitTitle
  opacity = 1.0 override 1.0 override
  opaque = true
}

# Tagging
windowrule {
  name = tag-vivaldi-settings
  match:title = ^([vV]ivaldi)(\s)(Settings\:)(.*)(-\s)?([vV]ivaldi)?$
  tag = +vSettingsInitTitle
}

windowrule {
  name = opacity-tagged-vivaldi-settings
  match:tag = vSettingsInitTitle
  opacity = 1.0 override 1.0 override
  opaque = true
}

windowrule {
  name = float-tagged-vivaldi-settings
  match:tag = vSettingsInitTitle
  float = true
  center = true
  size = 1200 1100
  persistent_size = true
}

# Tagging
windowrule {
  name = tag-vivaldi-webapp
  match:class = ^([vV]ivaldi)(-?)+(.*)(-?)+([dD]efault)$
  match:tag = vbrowserInitTitle
  tag = +vwebapp-general
}

windowrule {
  name = float-tagged-vivaldi-webapp
  match:tag = vwebapp-general
  pseudo = true
  float = true
  persistent_size = true
  opaque = true
}

# Vivaldi
