
## Main window
# mapped: 1
# hidden: 0
# at: 1031,53
# size: 3058,1382
# workspace: 1 (1)
# floating: 0
# pseudo: 0
# monitor: 0
# class: vivaldi-stable
# title: What's New in Vivaldi - Vivaldi
# initialClass: vivaldi-stable
# initialTitle: Vivaldi - Vivaldi
# pid: 35197
# xwayland: 0
# pinned: 0
# fullscreen: 0
# fullscreenClient: 0
# grouped: 0
# tags:
# swallowing: 0
# focusHistoryID: 0
# inhibitingIdle: 0
# xdgTag:
# xdgDescription:

# initialTitle: Vivaldi - Vivaldi

######### main window
windowrule = tag +vbrowserInitClass,initialClass:^([vV]ivaldi-stable?)$
windowrule = tag +vbrowserInitTitle,initialTitle:^([vV]ivaldi(\s*)-(\s*)[vV]ivaldi)$
# ^([vV]ivaldi)(\s+)(-?[vV]ivaldi)?$

# no idea why this one isn't applying via `hyprctl activewindow`, but 
# behaviour is correct for now
windowrule = workspace 1 silent,tag:vbrowserInitTitle
windowrule = workspace 1 silent,tag:vbrowserInitClass

# windowrule = noinitialfocus,tag:vbrowserInitClass,tag:vbrowserInitTitle

windowrule = opacity 1.0 override 1.0 override,tag:vbrowserInitClass,tag:vbrowserInitTitle
windowrule = opaque,tag:vbrowserInitClass

## Settings window 
#
# at: 1989,288
# size: 1141,864
# class: vivaldi-stable
# title: Vivaldi Settings: General - Vivaldi
# initialClass: vivaldi-stable
# initialTitle: Vivaldi Settings: General - Vivaldi

######### settings floating window
windowrule = tag +vSettingsInitTitle,title:^([vV]ivaldi)(\s)(Settings\:)(.*)(-\s?[vV]ivaldi)?$

windowrule = opacity 1.0 override 1.0 override,tag:vSettingsInitTitle
windowrule = opaque,tag:vSettingsInitTitle
windowrule = pseudo,tag:vSettingsInitTitle
windowrule = center, float,size 1200 1100,tag:vSettingsInitTitle
windowrule = persistentsize,tag:vSettingsInitTitle
# windowrule = stayfocused,tag:vSettingsInitTitle


######### web app window(s) spawned outside of vivaldi
windowrule = tag +vwebapp,class:^([vV]ivaldi).*(-?[dD]efault)$
windowrule = pseudo,tag:vwebapp
windowrule = float,tag:vwebapp
windowrule = persistentsize,tag:vwebapp
windowrule = opaque,tag:vwebapp
