windowrule {
  name = float-waypaper
  match:class = ^(waypaper)$
  float = true
  center = true
  size = 1450 1000
  persistent_size = true
}

# Waypaper

# windowrule = float,class:^(waypaper)$
# windowrule = size 1450 1000,class:^(waypaper)$
