# class: vivaldi-ggjocahimgaohmigbfhghnlfcnjemagj-Default
# title: Grok
# initialClass: vivaldi-ggjocahimgaohmigbfhghnlfcnjemagj-Default
# initialTitle: Grok

# vivaldi / web app / webapp / default

windowrule {
  name = tag-vivaldi-webapp-grok
  # match:class = ^([vV]ivaldi-?)(.*)(-+)(-?[dD]efault)$
  match:class = ^([vV]ivaldi)(-)(.*)(-)([dD]efault)$
  match:initial_class = ^([vV]ivaldi)(-)(.*)(-)([dD]efault)$
  match:title = ^([gG]rok)$
  match:initial_title = ^([gG]rok)$
  tag = +vwebapp-grok
}

windowrule {
  name = vivaldi-webapp-grok
  match:tag = vwebapp-grok
  size = 1000 1300
  move = 45 95
  pseudo = true
  float = true
  persistent_size = true
  opaque = vwebapp-grok
}

# Vivaldi webapp grok / WebApp / Webapp / web app / Web App / Grok / grok
