windowrule {
  name = float-webapp-manager
  match:class = ^(webapp-manager.py)$
  match:title = ^(Web Apps)$
  float = true
  size = 1000 650
}

windowrule {
  name = float-webapp-generic
  match:class = ^(WebApp-.*)$
  float = true
  size = 1450 1000
}

# WebappManager / Web App Manager / webapp

### windowrule = float,class:^(webapp-manager.py)$,title:^(Web Apps)$
### windowrule = size 1000 650,class:^(webapp-manager.py)$,title:^(Web Apps)$
### 
### windowrule = float,class:^(WebApp-.*)$
### windowrule = size 1450 1000,class:^(WebApp-.*)$


####### This is under ./vivaldi.conf
#
# ######### web app window(s) spawned outside of vivaldi
# windowrule = tag +vwebapp,class:^([vV]ivaldi).*(-?[dD]efault)$
# windowrule = pseudo,tag:vwebapp
# windowrule = float,tag:vwebapp
# windowrule = persistentsize,tag:vwebapp
# windowrule = opaque,tag:vwebapp
