windowrule {
  name = float-wezterm
  match:class = ^(org\.wezfurlong\.wezterm)$
  pseudo = true
  center = true
  size = 2280 1000
}

# TODO: There is the dispatch that can 
# 'create' / 'do' something on first entry to a workspace (workspace 2 in my case?)
#
# windowrule = float,class:^(org\.wezfurlong\.wezterm)$
### windowrule = pseudo,class:^(org\.wezfurlong\.wezterm)$
### windowrule = center,class:^(org\.wezfurlong\.wezterm)$,
### windowrule = size 2280 1000,class:^(org\.wezfurlong\.wezterm)$,
# windowrule = size 2200 1000,class:^(org\.wezfurlong\.wezterm)$,
# windowrule = size 1760 850,class:^(org\.wezfurlong\.wezterm)$,
