windowrule {
  name = tag-ytm
  match:class = ^com.github.th_ch.youtube.+$
  tag = +ytm
}

windowrule {
  name = workspace-ytm
  match:tag = ytm
  workspace = 8 silent
}

windowrule {
  name = float-ytm
  match:tag = ytm
  # float = true
  center = true
  size = 1250 850
  persistent_size = true
  maximize = true
}

## YouTube Music / youtube-music / YT

### windowrule = tag +ytm,class:^com.github.th_ch.youtube.+$
### windowrule = workspace 9 silent,tag:ytm
### windowrule = center,tag:ytm
# class:^(com.github.th_ch.youtube_music)$
# windowrule = float,class:^(com.github.th_ch.youtube_music)$
# windowrule = center,class:^(com.github.th_ch.youtube_music)$
### windowrule = persistentsize,tag:ytm
# class:^(com.github.th_ch.youtube_music)$
### windowrule = size 1250 850,tag:ytm
# class:^(com.github.th_ch.youtube_music)$
# windowrule = noinitialfocus,tag:ytm
# class:^(com.github.th_ch.youtube_music)$
