windowrule {
  name = tag-zed-editor
  match:class = ^(dev.[zZ]ed\.?[zZ]ed)$
  tag = +zedEditor
}

windowrule {
  name = tag-zed-editor-settings
  match:class = ^(dev.[zZ]ed\.?[zZ]ed)$
  match:title = ^(Zed\s(.*)[sS]ettings)$
  tag = +zedEditorSettings
}

windowrule {
  name = workspace-zed-editor
  workspace = 3 silent
  no_initial_focus = true
}

windowrule {
  name = pseudo-zed-editor
  match:tag = zedEditor
  # pseudo = true
  persistent_size = true
  size = 2950 1350
  ##### Focused   Unfocused
  # opacity = 1.0 override 1.0 override
  opacity = 1.0 override 0.85 override
  # opacity = 0.80 override 0.70 override
}

windowrule {
  name = float-zed-editor-settings
  match:tag = zedEditorSettings
  # pseudo = true
  persistent_size = true
  size = 1050 1050
  float = true
  opacity = 1.0 override 1.0 override
}


# Window 55abe181d320 -> Zed — Settings:
# 	mapped: 1
# 	hidden: 0
# 	at: 3068,176
# 	size: 1098,1103
# 	workspace: 2 (2)
# 	floating: 1
# 	monitor: 0
# 	class: dev.zed.Zed
# 	title: Zed — Settings
# 	initialClass: dev.zed.Zed
# 	initialTitle: Zed — Settings
# 	pid: 834066
# 	xwayland: 0
# 	pinned: 0
# 	fullscreen: 0
# 	fullscreenClient: 0
# 	overFullscreen: 1
# 	grouped: 0
# 	tags: zedEditor*
# 	swallowing: 0
# 	focusHistoryID: 0
# 	inhibitingIdle: 0
# 	xdgTag:
# 	xdgDescription:
# 	contentType: none
# 	stableID: 1800001b







# Zed / zed editor

# windowrule = opacity 1.00,class:^(zed-editor)$
### windowrule = workspace 3,class:^(dev.[zZ]ed\.?[zZ]ed)$

### windowrule = persistentsize,class:^(dev.[zZ]ed\.?[zZ]ed)$
# windowrule = float,class:^(dev.[zZ]ed\.?[zZ]ed)$
### windowrule = pseudo,class:^(dev.[zZ]ed\.?[zZ]ed)$
### windowrule = size 2950 1350,class:^(dev.[zZ]ed\.?[zZ]ed)$
### windowrule = opacity 1.0 override 1.0 override,class:^(dev.[zZ]ed\.?[zZ]ed)$
