
# windowrule = opacity 1.00,class:^(zed-editor)$
# Zed / zed editor
windowrule = workspace 3,class:^(dev.[zZ]ed\.?[zZ]ed)$
windowrule = persistentsize,class:^(dev.[zZ]ed\.?[zZ]ed)$
# windowrule = float,class:^(dev.[zZ]ed\.?[zZ]ed)$
windowrule = pseudo,class:^(dev.[zZ]ed\.?[zZ]ed)$
windowrule = size 2950 1350,class:^(dev.[zZ]ed\.?[zZ]ed)$
windowrule = opacity 1.0 override 1.0 override,class:^(dev.[zZ]ed\.?[zZ]ed)$

