
# ZenBrowser / Zen Browser / Zen

# class: zen
# title: Tridactyl Top Tips & New Tab Page — Zen Browser
# initialClass: zen
# initialTitle: Zen Browser

windowrule = tag +zbrowserInitClass,class:^[zZ]en(-?[bB]rowser)?$
windowrule = tag +zbrowserInitTitle,class:^[zZ]en(-?[bB]rowser)?$

windowrule = workspace 1 silent,tag:zbrowserInitClass
windowrule = opacity 1.0 override 1.0 override,tag:zbrowserInitClass
# windowrule = noinitialfocus,tag:zbrowserInitClass,initial-title:zbrowserInitClass

## This causes all kinds of weirdness - constantly calls out for focus (ie: Qalculate popups will move to zen etc.)
# windowrule = stayfocused,tag:zbrowserInitClass,initial-title:zbrowserInitClass

## Additional window spawns are incredibly buggy - eg: Bookmark manager (named as: Library) and others.
#
## We need to unset the 'stayfocused' when another window the `title:Library` or `initialTitle: Library`
## is present, as they're pop-ups, but you can't interact with them properly if the main window is focused

## windowrule = unset stayfocused, tag:zbrowserInitClass, title:^(Library)$
## windowrule = unset stayfocused, tag:zbrowserInitClass, initialTitle:^(Library)$
## windowrule = stayfocused, tag:zbrowserInitClass, title:^(Library)$
## windowrule = stayfocused, tag:zbrowserInitClass, initialTitle:^(Library)$ 
##
## windowrule = workspace 1,class:^(zen(-browser)?)$
## windowrule = opacity 1.0 override 1.0 override,class:^(zen(-browser)?)$
##
## windowrule = noinitialfocus,class:^(zen(-browser)?)$, # allows spawning it via mod + b, without swapping
## windowrule = stayfocused, tag:zbrowserInitClass
## windowrule = noblur,class:^(zen(-browser)?)$
## windowrule = pseudo,class:^(zen(-browser)?)$
## windowrule = size 2660 1300,class:^(zen(-browser)?)$,
## windowrule = float,class:^(zen.*)$,title:^(Picture-in-Picture)$
## # windowrule = stayfocused,class:^(zen(-browser)?)$
