#######################################################
### This entire file is managed entirely by wallust ###
#######################################################

$wallpaper = {{ wallpaper }},/home/dwarf/Pictures/wallpapers/wallhaven-mdjrqy.jpg,/home/dwarf/Pictures/wallpapers/wallhaven-zp8m8o.jpg

preload = $wallpaper
wallpaper = , contain:$wallpaper
