local o = vim.opt
o.number = true -- sets vim.opt.number
o.clipboard = "unnamedplus" -- connection to the system clipboard
o.copyindent = true -- copy the previous indentation on autoindenting
o.cursorline = true -- highlight the text line of the cursor
o.expandtab = true -- enable the use of space in tab
o.foldenable = true -- enable fold for nvim-ufo
o.foldlevel = 99 -- set high foldlevel for nvim-ufo
o.foldlevelstart = 99 -- start with all code unfolded
o.history = 100 -- number of commands to remember in a history table
o.ignorecase = true -- case insensitive searching
o.infercase = true -- infer cases in keyword completion
o.laststatus = 3 -- global statusline
o.linebreak = true -- wrap lines at 'breakat'
o.preserveindent = true -- preserve indent structure as much as possible
o.pumheight = 12 -- height of the pop up menu
o.shiftwidth = 4 -- number of space inserted for indentation
o.showmode = false -- disable showing modes in command line
o.showtabline = 2 -- always display tabline
o.smartcase = true -- case sensitive searching
o.splitbelow = true -- splitting a new window below the current one
o.splitright = true -- splitting a new window at the right of the current one
o.tabstop = 4 -- number of space in a tab
o.termguicolors = true -- enable 24-bit RGB color in the TUI
o.timeoutlen = 300 -- shorten key timeout length a little bit for which-key
o.undofile = true -- enable persistent undo
o.updatetime = 100 -- length of time to wait before triggering the plugin
o.virtualedit = "block" -- allow going past end of line in visual block mode
o.writebackup = false -- disable making a backup before overwriting a file
o.incsearch = true
o.backup = false
o.cmdheight = 1
o.hlsearch = true
o.smartindent = true
o.splitkeep = "screen"
o.swapfile = false
o.softtabstop = 4
o.numberwidth = 4
o.scrolloff = 10 --Scrolloff maintains a margin at top or bottom of screen.
o.sidescrolloff = 10
o.showcmd = false --May want to play around with this one
o.ruler = false
o.guifont = "CaskaydiaCove Nerd Font Mono:h12"
o.title = true
o.confirm = true
o.list = true
o.cursorlineopt = "line"
o.shell = "pwsh"
o.shellcmdflag =
	"-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;"
o.shellredir = "-RedirectStandardOutput %s -NoNewWindow -Wait"
o.shellpipe = "2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode"
o.shellquote = ""
o.shellxquote = ""
