# Agent changes require a restart via:
# gpg-connect-agent reloadagent /bye
#
# Assuming it prints 'OK' it worked.
#
# default-cache-ttl 3600 ## seconds - 1 hour
# Allows single pass per login session unless the gpg-agent is killed/reset
allow-preset-passphrase

# seconds - 1 day
default-cache-ttl 86400
# seconds - 7 days
max-cache-ttl 604800

# Allows (although buggy) pinetry to basically echo the pass back to itself internally via stdout->stdin loopback
allow-loopback-pinentry
