# rustic config file to backup /home, /etc and /root to a local repository
# `-P <profile>` below can be filled if if using a file that is not the rustic.toml default.
# `--name <name>` can be used to specify a specific item in the backup. snapshots array to backup. If not specified, all items will be backed up.
#
# backup usage: "rustic backup
# cleanup:      "rustic forget --prune
#
# global options: These options are used for all commands.
[global]
log-level = "debug"
# log-file = "/var/log/rustic/2025_07_08__2.log"

## Allows to recursively include other configuration files.
# use-profiles = [
#   #
#   "root-only",
#   "local-user",
#   # etc.
# ]


[repository]
repository = "/mnt/linux_data/rustic/"
# password-file = "/root/.secret/rustic_secret"
password-file = "/home/dwarf/.secret/rustic_secret"

no-cache = true # no cache needed for local repository

[forget]
keep-hourly = 6
keep-daily = 8
keep-weekly = 4
keep-monthly = 6
keep-yearly = 1

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
one-file-system = true

[[backup.snapshots]]
name = "home"
sources = ["/home"]
git-ignore = false
# glob-files = ["/home/dwarf/.config/rustic/rustic.glob-excludes.glob"]

## Glob is naturally case sensitive
# glob-files = ["/home/dwarf/.config/rustic/all.glob-excludes.glob"]
## Case insensitive glob matching
iglob-files = ["/home/dwarf/.config/rustic/all.glob-excludes.glob"]

[[backup.snapshots]]
name = "etc"
sources = ["/etc"]

[[backup.snapshots]]
name = "root"
sources = ["/root"]
