# Default download dir (in case forgetting output)
dir=${HOME}/downloads/aria

# Specify share ratio. Seed completed torrents until share ratio reaches RATIO.
# You are strongly encouraged to specify equals or more than 1.0 here.
# Specify 0.0 if you intend to do seeding regardless of share ratio.
# If --seed-time option is specified along with this option,
# seeding ends when at least one of the conditions is satisfied.
# Default: 1.0
seed-ration=1.0

# Specify seeding time in (fractional) minutes. Also see the --seed-ratio option.
seed-time=30

# Speed up some downloads
disable-ipv6=true

# Download a file using N (16) connections
split=16

# The maximum number of parallel downloads for every static (HTTP/FTP) URL.
max-concurrent-downloads=10

# The maximum number of connections to one server for each download
max-connection-per-server=16

# Enable disk cache. If SIZE is 0, the disk cache is disabled.
# Using disk cache improves performance because it reduces disk I/O operations.
# (K = 1k == 1024, M = 1M == 1024K etc.)
# Default: 16M
disk-cache=16M


file-allocation=falloc

# Requires file-allocation of some sort
enable-mmap=true

# Enable local peer discovery for BitTorrent downloads.
bt-enable-lpd=true
