# vim:set ft=tmux: sw=2 ts=2 sts=2 et:
## DESIGN TWEAKS

set -g window-status-current-style "bg=#{@color-primary},fg=#{@color-text},bold"
setw -g window-status-current-format ' #I #W #F ' # Active

set -g window-status-style "bg=0,fg=white"
setw -g window-status-format ' #[fg=white]#I #[fg=#{@color-secondary}]#W #[fg=#{@color-accent}]#F ' # inactives

set -g pane-active-border-style 'fg=#{@color-primary},bg=default' # active
set -g pane-border-style 'fg=#{@color-secondary},bg=default' # inactive

## 

set -g status-bg #{@color-text}
set -g status-fg white
set -g status-left ""
# set -g status-right "#[fg=#{@color-primary}]#H #[fg=#{@color-accent}]%I:%M %p #[fg=#{@color-secondary}]%Y-%m-%d "
set -g status-right " #[fg=#{@color-primary}]#H #[fg=#{@color-secondary}]| #[fg=#{@color-accent}]%I:%M #[fg=#{@color-secondary}]%Y-%m-%d "

## TODO: make less ugly af later
## Messages

# set -g message-style 'fg=black bg=green'
set -g message-style 'bg=#{@color-text},fg=white'


