# vim:set ft=tmux: sw=2 ts=2 sts=2 et:
## DESIGN TWEAKS

# - #I == Number of tab
# - #W == What's running in it
# - #F == special icon for current and previous tabs

source-file -q "$XDG_CONFIG_HOME/tmux/vars.conf"

set -g status-position top

set -g window-status-current-style "bg=#{@color-primary},fg=#{@color-text},bold"

# b: is the basename
# d: is the dirname

# S1 :: if pane_current_path != user, then render the pane_current_path, otherwise render ~
# S2 :: if @shell_var != #W, then render #W, otherwise render nothing

#                                           | S1                                                          |  | S2                       |
setw -g window-status-current-format ' #I//#{?#{==:#{b:pane_current_path},#{user}},~,#{b:pane_current_path}} #{?#{!=:#{@shell_var},#W},#W,}#F |'
set -g window-status-style "bg=0,fg=white"

# │
setw -g window-status-format '#I#[fg=#{@color-accent}]//#[fg=white]#{?#{==:#{b:pane_current_path},#{user}},~,#{b:pane_current_path}} #[fg=#{@color-secondary}]#{?#{!=:#{@shell_var},#W},#W}#[fg=#{@color-accent}]#F#[fg=white] │' # Inactive

set -g pane-active-border-style 'fg=#{@color-primary},bg=default' # active
set -g pane-border-style 'fg=#{@color-secondary},bg=default' # inactive

# setw -g pane-border-format ' #{=/-20/…:pane_title} [#{=/-20/…:pane_current_command}] #(pgrep -P "#{pane_pid}" | tr "\n" " ")#{pane_current_path} #{?alternate_on,<Alt Mode> ,}'

set -g status-style 'bg=#{@color-text},fg=#{@color-primary}'
set -g status-left ''

# %I:%M %Y-%m-%d
#
# %I - 12^ hour format
# %M - minutes
# %Y - year
# %m - numbered month (with leading zero)
# %d - day of month
set -g status-right " #[fg=#{@color-primary}]#H #[fg=white]| #S #[fg=#{@color-secondary}]| "

set -g message-style 'bg=#{@color-text},fg=white'
