# vim:set ft=tmux: sw=2 ts=2 sts=2 et:


############
## Basics ##
############

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config file (change file location to your the tmux.conf you want to use)
bind r command-prompt "rename-window %%"
bind R source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded!"

unbind D
unbind d
bind d kill-pane
bind D detach-client
# Test to see if this is more or less awk.

bind C-p previous-window          # We double up so that (Ctrl-a + Ctrl-p) is same as ctrl-a + p
bind C-n next-window              # same here

# split panes using | and -
unbind '"'
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind "`" last-window # Tapping ctrl-a + backtick will pop you between the last two used windows
bind C-a last-window # Tapping ctrl-a + a will pop you between the last two used windows
# bind a last-window # Tapping ctrl-a + a will pop you between the last two used windows

## Custom bind for - windows/tabs to spawn in $HOME, not the directory in which tmux was launched
bind ^C new-window -c "$HOME"
bind c new-window -c "#{pane_current_path}" # not entirely needed, but forces

bind y copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi C-q send-keys -X rectangle-toggle
bind-key -T copy-mode-vi H send-keys ^
bind-key -T copy-mode-vi L send-keys $
# bind-key -T copy-mode-vi Escape send-keys -X ####### how to do like, double-escape? maybe just 'copy-pipe' ?


##############################
## Extra stuff and fiddling ##
##############################

unbind "'"
# bind "'" select-pane -t :.+ # Cycle through panes
bind "'" switch-client -t '{marked}'

bind b choose-window 'join-pane -h -s "%%"' # Horizontally - The reverse of a 'breakout' (prefix + !) - joins a window as a pane, into another window (choose from picker)
bind v choose-window 'join-pane -s "%%"' # Vertically - The reverse of a 'breakout' (prefix + !) - joins a window as a pane, into another window (choose from picker)

bind P set pane-border-status # Sort of a 'mini-status' of what the pane is doing

# bind e set -g status # To toggle the bar off and on

bind-key x kill-pane # Skip the confirmation dialog thing

# Getting around panes (Same as wezterm)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r -T root C-Left resize-pane -L 8
bind -r -T root C-Right resize-pane -R 8
bind -r -T root C-Down resize-pane -D 4
bind -r -T root C-Up resize-pane -U 4

# Unbind default bindings for prefix , and prefix .
unbind-key , # previously was 'rename-window' (+ filling in the existing name of it)
unbind-key . # move-window

bind -r , swap-window -d -t -1
bind -r . swap-window -d -t +1

## Other way to do it, but why use below when you can do above?
## bind-key , swap-window -t -1 \; select-window -t -1
## # Bind prefix . to move window right
## bind-key . swap-window -t +1 \; select-window -t +1

bind-key u run-shell -b "tmux-url-select"
# bind-key O run-shell -b "tmux-url-select full"


## TODO: bruh.... contextual rename howww?????????????????

# unbind-key -T tree-mode r
# Bind 'r' in tree-mode to contextual rename of the selected item
# bind-key -T tree-mode r if -F "#{pane_id}" "command-prompt -p 'rename-pane:' 'select-pane -t \"#{pane_id}\" -T \"%%\"'" "if -F \"#{window_id}\" \"command-prompt -p 'rename-window:' 'rename-window -t \"#{window_id}\" \"%%\"'\" \"command-prompt -p 'rename-session:' 'rename-session -t \"#{session_id}\" \"%%\"'\""
