# vim:set ft=tmux: sw=2 ts=2 sts=2 et:


############
## Basics ##
############

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set-option -g prefix C-b
# bind-key C-b send-prefix


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded!"
bind R command-prompt "rename-window %%"

unbind D
unbind d
bind d kill-pane
bind D detach-client

bind C-p previous-window          # We double up so that (Ctrl-a + Ctrl-p) is same as ctrl-a + p
bind C-n next-window              # same here

# split panes using | and -
unbind '"'
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind "`" last-window # Tapping ctrl-a + backtick will pop you between the last two used windows
bind C-a last-window # Tapping ctrl-a + a will pop you between the last two used windows
bind a last-window

## Custom bind for - windows/tabs to spawn in $HOME, not the directory in which tmux was launched
bind ^C new-window -c "$HOME"
bind c new-window -c "#{pane_current_path}" # not entirely needed, but forces

bind y copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi C-q send-keys -X rectangle-toggle
bind-key -T copy-mode-vi H send-keys ^
bind-key -T copy-mode-vi L send-keys $
# bind-key -T copy-mode-vi Escape send-keys -X ####### how to do like, double-escape? maybe just 'copy-pipe' ?


##############################
## Extra stuff and fiddling ##
##############################

unbind "'"
# bind "'" select-pane -t :.+ # Cycle through panes
bind "'" switch-client -t '{marked}'

# C-a, ! -- is to breakout a pane (Will also move it to the end if there's only one pane)
# C-a, C-o -- rotate window/panes
# C-a, space -- rotate layouts

# join veritcally (from some other window/tab)
bind _ choose-window 'join-pane -s "%%"'
# join horizontally (from some other window/tab)
bind | choose-window 'join-pane -h -s "%%"'

bind P set pane-border-status # Sort of a 'mini-status' of what the pane is doing
bind g set -g status # To toggle the bar off and on

bind-key x kill-pane # Skip the confirmation dialog thing

# Getting around panes (Same as wezterm)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r -T root C-Left resize-pane -L 8
bind -r -T root C-Right resize-pane -R 8
bind -r -T root C-Down resize-pane -D 4
bind -r -T root C-Up resize-pane -U 4

# Unbind default bindings for prefix , and prefix .
unbind-key , # previously was 'rename-window' (+ filling in the existing name of it)
unbind-key . # move-window

bind -r , swap-window -d -t -1
bind -r . swap-window -d -t +1

# List sessions based on last used time
# tmux choose-tree -Zs
# -Z[type] -> s: sessions collapsed, w: windows collapsed
# -O[how] -> 'index' | 'name' | 'time'
bind -r s choose-tree -O 'time' -Zs
# 's' was originally this (swapped them)
# bind -r S choose-tree -Zs
# bind -n M-W command-prompt "rename-session '%%'"
bind-key u run-shell -b "tmux-url-select"

bind -r S command-prompt "rename-session '%%'"

## TODO: bruh.... contextual rename howww?????????????????
#
# to rename a session in the (choose-tree -Zs) mode
# We need to: 
# 1- check if we're in the choose-tree mode/menu/picker 
# 2-get the session_id to target it
# 3-run the command-prompt to rename it
# 3/ - could also use similar to 'send-keys'? ( :rename-session <name> )
