# vim:set ft=tmux: sw=2 ts=2 sts=2 et:


set-option -g @color-primary 'magenta'
set-option -g @color-accent 'blue'
set-option -g @color-secondary 'brightblack'
set-option -g @color-text 'black'

set-option -g @copy-program 'xsel -i'

## We use a tmux variable _specifically_ to prevent tmux from spawning a damn sh shell every loop check
# tldr it's caching.
set-option -g @shell_var "$SHELL"
