# vim:set ft=tmux: sw=2 ts=2 sts=2 et:

# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# PARENT_DIR="$(dirname "$DIR")"
#
# run-shell -q |xyzsxasdasd|
#

set-option -g @color-primary 'magenta'
set-option -g @color-accent 'blue'
set-option -g @color-secondary 'brightblack'
set-option -g @color-text 'black'

set-option -g @copy-program 'xsel -i'
