#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


source = ./map_general.conf
source = ./map_misc.conf
source = ./map_programs.conf
source = ./map_programs_hypr.conf
source = ./map_windows_workspaces.conf

# source = ./submap_move_to_workspace.conf
# source = ./submap_resize_win.conf
# source = ./submap_shift_win.conf
# source = ./submap_workspace.conf
