#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


##############################
### WINDOWS AND WORKSPACES ###
##############################

#### Arrows used for workspace stuff ####
#### Letters used for in the current viewport/workspace ####

# Move current focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

# I hot these way too often not to just bind them honestly
# bind = $mainMod, y, movefocus, l
# bind = $mainMod, o, movefocus, r


#######################
### shift_win_binds ###
#######################

# Move it around on the current screen
bind = $mainModShift, h, movewindow, l
bind = $mainModShift, j, movewindow, d
bind = $mainModShift, k, movewindow, u
bind = $mainModShift, l, movewindow, r

# Swapping between worskapces - same behaviour as eg: pressing same workspace number again
bind = $mainMod, w, workspace, previous
bind = $mainMod, Tab, workspace, previous
# bind = $mainModShift, Tab, workspace, previous ### idk wtf this is doing lmao

###########################
### shift_win_binds END ###
###########################





########################
### resize_win_binds ###
########################

binde = $mainModCtrl, h, resizeactive, -50 0
binde = $mainModCtrl, j, resizeactive, 0 50
binde = $mainModCtrl, k, resizeactive, 0 -50
binde = $mainModCtrl, l, resizeactive, 50 0

binde = $mainModCtrl, left, resizeactive, -50 0
binde = $mainModCtrl, down, resizeactive, 0 50
binde = $mainModCtrl, up, resizeactive, 0 -50
binde = $mainModCtrl, right, resizeactive, 50 0

############################
### resize_win_binds END ###
############################





#######################
### workspace_binds ###
#######################

## Move view to a workspace
# inners are swapped technically - each forms a pair
bind = $mainMod, left, workspace, e-1
bind = $mainMod, down, workspace, e+1

bind = $mainMod, up, workspace, e-1
bind = $mainMod, right, workspace, e+1

# Absolute
## Move view to a workspace - number keys
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

###########################
### workspace_binds END ###
###########################





###############################
### move_to_workspace_binds ###
###############################

# Relative
## Move window to workspace
bind = $mainModShift, left, movetoworkspace, e-1
bind = $mainModShift, down, movetoworkspace, e-1
bind = $mainModShift, up, movetoworkspace, e+1
bind = $mainModShift, right, movetoworkspace, e+1

bind = $mainMod, mouse_down, workspace, e-1
bind = $mainMod, mouse_up, workspace, e+1

# Absolute - number keys
bind = $mainModShift, 1, movetoworkspace, 1
bind = $mainModShift, 2, movetoworkspace, 2
bind = $mainModShift, 3, movetoworkspace, 3
bind = $mainModShift, 4, movetoworkspace, 4
bind = $mainModShift, 5, movetoworkspace, 5
bind = $mainModShift, 6, movetoworkspace, 6
bind = $mainModShift, 7, movetoworkspace, 7
bind = $mainModShift, 8, movetoworkspace, 8
bind = $mainModShift, 9, movetoworkspace, 9
bind = $mainModShift, 0, movetoworkspace, 10

bind = $mainMod, Tab, workspace, next,
bind = $mainModShift, Tab, workspace, previous

###################################
### move_to_workspace_binds END ###
###################################
