#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################

# Prorams here are mostly utilities 
# that are needed when running in a non-quickshell type env.
# We do this so we can source the other 
# 'map_programs.conf' file without conflicts in binds.

bind = $mainMod, r, exec, $menu
bind = $mainModShift, r, exec, $menu_other
bind = $mainMod, u, exec, $locking
bind = $mainMod, m, exec, $logout_prog

bind = $mainModCtrl, a, exec, $notifications -t -sw || swaync-client -t -sw
bind = $mainModShift, s, exec, $screenshot "full" # Immedite fullscreen, and writes out normal Pictures/Screenshots/
bind = $mainModCtrl, s, exec, $screenshot "region" # Similar - but uses slurp to hold the screen capture/selection

bind = $mainModCtrl, v, exec, $clipboard_history
