#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


bind = $mainMod, t, exec, $term
bind = $mainModShift, t, exec, $second_term
bind = $mainModAlt, t, exec, kitty # Mostly a safety measure lol
bind = $mainMod, r, exec, $menu
bind = $mainModShift, R, exec, $menu_other
bind = $mainMod, e, exec, $fileManager
bind = $mainMod, u, exec, $locking
bind = $mainMod, b, exec, $browser
bind = $mainMod, m, exec, $logout_prog

bind = $mainModCtrl, A, exec, $notifications -t -sw || swaync-client -t -sw
bind = $mainMod, s, exec, $screenshot "full" # Immedite fullscreen, and writes out normal Pictures/Screenshots/
bind = $mainModCtrl, S, exec, $screenshot "region" # Similar - but uses slurp to hold the screen capture/selection

bind = $mainModShift, v, exec, $clipboard_history
bind = $mainModShift, c, exec, $color_picker
