#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


bind = CTRL ALT, Delete, exec, uwsm stop
# exit

# Can define via exec/IPC call (Though this has some performance overhead compared to chaining commands)
# bind = $mainMod, q, exec, hyprctl dispatch killactive && hyprctl dispatch focusmonitor 0

# Or can 'chain' shortcuts.

#### IMPORTANT START ####
#
# If doing this - they MUST remain in the same order.
# Hyprland will execute them (filewise) top to bottom.
bind = $mainMod, q, killactive,
bind = $mainMod, q, focusmonitor, 0

#### IMPORTANT END ####

bind = $mainMod, f, togglefloating,
bind = $mainMod, c, centerwindow,

bind = $mainMod, p, pin 

# groups
bind = $mainModShift, g, lockgroups, toggle
bind = $mainMod, g, togglegroup

bind = $mainMod, Home, changegroupactive, b
bind = $mainMod, End, changegroupactive, f

bind = $mainMod, s, pseudo # dwindle || maintains the 'space' for a 'floated' window

# ## TODO: Error'ing
# bind = $mainMod, Space, togglesplit # dwindle

bind = $mainModShift, f, fullscreen, 1
## Allow swapping when using 'master' layout method
bind = $mainModCtrl, f, layoutmsg, swapwithmaster master

bind = ALT, Tab, cyclenext
bind = ALT, Tab, bringactivetotop    # bring it to the top

