#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


bind = $mainMod, t, exec, $term
bind = $mainModShift, t, exec, $second_term
bind = $mainModAlt, t, exec, kitty # Mostly a safety measure lol

bind = $mainMod, b, exec, $browser
bind = $mainMod, e, exec, $file_manager
bind = $mainModShift, c, exec, $color_picker
