#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


########################
### resize_win_binds ###
########################

##############
### Submap ###
##############

bind = $submapMod, r, submap, resize

submap = resize

binde = , h, resizeactive, -50 0
binde = , j, resizeactive, 0 50
binde = , k, resizeactive, 0 -50
binde = , l, resizeactive, 50 0

# use reset to go back to the global submap
bind = , escape, submap, reset
bind = , BackSpace, submap, reset
# bind = , $submapMod, submap, reset

# will reset the submap, which will return to the global submap
submap = reset

##################
### Submap END ###
##################

############################
### resize_win_binds END ###
############################
