#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


#######################
### workspace_binds ###
#######################

##############
### Submap ###
##############

bind = $submapMod, w, submap, workspaces

submap = workspaces

###################
# q1, w2, e3, | ## r4, t5
# a4, s5, d6, | ## f7, g8
# z7, x8, c9, | ## v10, b11
###################

# bind = , right, resizeactive, 10 0
bind = , q, workspace, 1
bind = , w, workspace, 2
bind = , e, workspace, 3

# extension setction
bind = , r, workspace, 4
bind = , t, workspace, 5

bind = , a, workspace, 4
bind = , s, workspace, 5
bind = , d, workspace, 6

# extension setction
bind = , f, workspace, 7
bind = , g, workspace, 8

bind = , z, workspace, 7
bind = , x, workspace, 8
bind = , c, workspace, 9

# extension setction
bind = , v, workspace, 10
bind = , b, workspace, 11

# use reset to go back to the global submap
bind = , escape, submap, reset
bind = , BackSpace, submap, reset
# bind = , $submapMod, submap, reset
bind = , j, submap, reset
bind = , k, submap, reset

# will reset the submap, which will return to the global submap
submap = reset

##################
### Submap END ###
##################

###########################
### workspace_binds END ###
###########################
