#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


###############################
### move_to_workspace_binds ###
###############################

##############
### Submap ###
##############

bind = $submapMod, t, submap, move_to_workspace

submap = move_to_workspace

###################
# q1, w2, e3, | ## r4, t5
# a4, s5, d6, | ## f7, g8
# z7, x8, c9, | ## v10, b11
###################

# bind = , right, resizeactive, 10 0
bind = , q, movetoworkspace, 1
bind = , w, movetoworkspace, 2
bind = , e, movetoworkspace, 3

# extension setction
bind = , r, movetoworkspace, 4
bind = , t, movetoworkspace, 5

bind = , a, movetoworkspace, 4
bind = , s, movetoworkspace, 5
bind = , d, movetoworkspace, 6

# extension setction
bind = , f, movetoworkspace, 7
bind = , g, movetoworkspace, 8

bind = , z, movetoworkspace, 7
bind = , x, movetoworkspace, 8
bind = , c, movetoworkspace, 9

# extension setction
bind = , v, movetoworkspace, 10
bind = , b, movetoworkspace, 11

# use reset to go back to the global submap
bind = , escape, submap, reset
bind = , BackSpace, submap, reset
# bind = , $submapMod, submap, reset
bind = , j, submap, reset
bind = , k, submap, reset

# will reset the submap, which will return to the global submap
submap = reset

##################
### Submap END ###
##################

###################################
### move_to_workspace_binds END ###
###################################
