#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################


#######################
### shift_win_binds ###
#######################

##############
### Submap ###
##############

bind = $submapMod, s, submap, shift_win

submap = shift_win

bind = , h, movewindow, l
bind = , j, movewindow, d
bind = , k, movewindow, u
bind = , l, movewindow, r

# use reset to go back to the global submap
bind = , escape, submap, reset
bind = , BackSpace, submap, reset
# bind = , $submapMod, submap, reset

# will reset the submap, which will return to the global submap
submap = reset

##################
### Submap END ###
##################

###########################
### shift_win_binds END ###
###########################
