---@meta
---@module 'utils.t'
---

-------------------------------------------------
---@class utils.Arch: utils.Base
--- `true` if the current OS is Windows, otherwise `false`
--- Checks both `vim.fn.has("win32")` and `has("win64")` versions.
---@field __IS_WIN boolean
---@field get_os fun(): EOperatingSystemEnum
---@field get_os_lower fun(): EOperatingSystemEnumLower
-------------------------------------------------

-------------------------------------------------
---@class utils.AutoFmt
---@field formatters_reset fun(): void
---@field toggle_autoformat fun(effect_global?: boolean, bufnr?: number): void
---@field setup fun(): utils.AutoFmt
-------------------------------------------------

-------------------------------------------------
---@class utils.BufDel: utils.Base
--- Safely handle buffer deletion operations.
--- Includes type checks and user prompts for unsaved changes.
---
--- Delete a buffer:
--- - either the current buffer if `buf` is not provided
--- - or the buffer `buf` if it is a number
--- - or every buffer for which `buf` returns true if it is a function
---@field delete fun(opts?: utils.BufDel.Opts): utils.BufDel|nil
--- Delete all buffers
---@field all fun(opts?: utils.BufDel.Opts): nil
--- Delete all buffers except the current one
---@field other fun(opts?: utils.BufDel.Opts): utils.BufDel|nil

---@class utils.BufDel.Opts
---@field buf? number Buffer to delete. Defaults to the current buffer
---@field file? string Delete buffer by file name. If provided, `buf` is ignored
---@field force? boolean Delete the buffer even if it is modified
---@field filter? fun(buf: number): boolean Filter buffers to delete
---@field wipe? boolean Wipe the buffer instead of deleting it (see `:h :bwipeout`)
-------------------------------------------------

-------------------------------------------------
---@generic P: PathBuf
---@generic W: WindowsPathBuf
---@class utils.Converter: utils.Base
---@field __tostring fun(): string
---@field __call fun(filepath: PathBuf): PathBuf
---
--- Pure function.
---
--- Strips leading and trailing slashes from a given filepath.
---@field strip fun(filepath: PathBuf): PathBuf
---
---
--- Pure function.
---
--- Transforms a *nix style path to a Windows style path.
--- Removes the leading `/` and replaces all `/` with `\`.
--- additionally adds the semicolon (`:`) required for Windows paths,
--- and removes the trailing `/` character.
---
--- Will take a string like:
--- `/C/Users/NAME/dotfiles/.config/nvim/`
--- and transform it to:
--- `C:\Users\NAME\dotfiles\.config\nvim`
---
---@field windows_path fun(d: PathBuf): WindowsPathBuf
---
--- Internal function.
--- Old logic, now deprecreated that both `fullpath` and `relative` exist.
--- Is still used as a fallback for other functions.
---
---@deprecated Use `utils.Converter.fullpath()` or `utils.Converter.relative()` instead.
---@field _filepath fun(): PathBuf
---
---@field fullpath fun(opts?: { filepath?: PathBuf }): PathBuf
---@field relative fun(opts?: { filepath?: PathBuf }): PathBuf
-------------------------------------------------

-------------------------------------------------

---@class utils.List
---@field find_qf fun(type: QfTypes): { winid: number, bufnr: number }[]
--- Open the quickfix window if it is not empty,
--- otherwise prints a message.
---@field open_qf fun(): nil
--- Open all loclist windows if they are not empty, otherwise prints a message.
--- Switches before calling `lopen` to ensure the correct window is opened.
---@field open_loclist_all fun(): nil
--- Toggle the quickfix or loclist window on or off, depending on the type passed.
---@field toggle_qf fun(type: QfTypes): nil
-------------------------------------------------

-------------------------------------------------
---@class WinTable
---@field winid number
---@field bufnr number
-------------------------------------------------

---@class utils.Output: utils.Base
--- `true` if the current Neovim version is `nvim-0.11`, otherwise `false`
---@field __HAS_NVIM_011 boolean
--
--
-- removed --- Set to the same value as `__IS_WIN`, but used to determine if snacks should be used.
--
-- removed ---@field __USE_SNACKS boolean
--
--
--- An info function that notifies messages, aware of fast events
---@field info fun(msg: MsgData|unknown): nil
--- A warning function that notifies messages, aware of fast events
---@field warn fun(msg: MsgData): nil
--- An err function that notifies messages, aware of fast events
---@field err fun(msg: MsgData): nil
--- Check if the current user is root (uid 0) (and not self.___IS_WIN, because, well... Windows)
---@field is_root fun(): boolean
--- Get the development directory, handles expanding the local variable
--- of DEV_DIR, with addational DEV_DIR_NAME appended to it.
--- These (at current) expand and handle both variations of [dD]ocuments:
--- `$HOME/Documents/nvim_dev` or `$HOME/documents/nvim_dev`.
---@field get_dev_dir fun(): string
--- Check if the provided path is a development directory,
--- uses `utils.Generic.get_dev_dir()` internally
---@field is_dev fun(path: string): boolean
--- Checks if a valid `C` compiler is available.
--- Checks against `cc`, `gcc`, `clang`, `cl`, and `zig`.
---@field have_compiler fun(): boolean
--- Checks if the `cargo` command has a nightly version available.
--- Uses `+nightly` to check.
---@field cargo_has_nightly fun(): boolean
--- Get the root of a git repository,
--- or the parent directory if no git repo is found.
---@field git_root fun(cwd: string?, noerr?: boolean): string?, integer?
--- Modify the current working directory to the provided path,
--- or to the parent directory of the current buffer if no path is provided.
---@field set_cwd fun(pwd: string?): nil
--- Get's the current visual selection,
--- or the last known visual selection if not in visual mode.
---@field get_visual_selection fun(nl_literal: boolean?): string
--- Find all quickfix or loclist windows,
--- depending on the type passed.
--- Print a string to the clipboard using OSC 52 (OSC 25).
---@field osc25printf fun(...: string): nil
--- Unload Lua modules matching the provided patterns.
---@field unload_modules fun(patterns: { mod: string, fn?: fun() }): nil
--- Reloads the the predefined config modules.
--- Patterns are already supplied inside this module (`utils.generic`)
--- @see utils.Generic.reload_config for the patterns used.
---@field reload_config fun(): nil
--- Check if a window is a floating window.
---@field win_is_float fun(winnr: number): boolean
--- Calls an input function, either `vim.ui.input` or `vim.fn.input`, depending on the Neovim version.
---@field input fun(prompt: string): string | nil
--- Version specific implementation of retreiving LSP clients.
--- If `nvim-0.11` is available, uses `vim.lsp.get_clients(opts)`
--- If not, fallback to loading clients into a local `via vim.lsp.buf_get_clients(opts.bufnr)`
--- Then setting the metatable for `supports_method`, `request`, and `request_sync`
---@field lsp_get_clients fun(opts: { bufnr?: number, id?: number }): vim.lsp.Client[]
-- local M = {}
-------------------------------------------------

-------------------------------------------------
---@class utils.Sudo: utils.Base
--- Registeres several user commands related to sudo operations.
---
--- Currently registers:
--- * `SudoWrite`,`SudoWrite!`
--- * `W`, `W!`
---
--- Allows users to write files with elevated permissions directly from Neovim
--- via the use of the above commands.
---@field register_user_commands fun(opts?: utils.Sudo.user_command.Opts): nil
---
--- Execute a command with `sudo`,
--- prompting for the password if necessary.
---@field sudo_exec fun(opts: utils.Sudo.sudo_exec.Opts): boolean
-- prev ---@field sudo_exec fun(cmd: string, print_output?: boolean): boolean
--
--- Execute a write command using `dd` and pre-set bytesize,
--- using `sudo` to write to the file.
---
--- Uses a temporary file to write the contents,
--- and then writes it to the specified file path
---@field sudo_write fun(opts?: utils.Sudo.sudo_write.Opts): nil
--
-- prev ---@field sudo_write fun(tmpfile?: string, filepath?: string): nil
-------------------------------------------------

-------------------------------------------------
---@class utils.Sudo.sudo_exec.Opts
---@field cmd string The command to execute with sudo
---@field print_output? boolean Whether to print the output of the command, defaults to false
-------------------------------------------------

-------------------------------------------------
---@class utils.Sudo.sudo_write.Opts
---@field tmpfile? string The temporary file to use for writing
---@field filepath? string The file path to write to with sudo
-------------------------------------------------

-------------------------------------------------
---@class utils.Base
---@field debugging boolean
-------------------------------------------------

-------------------------------------------------
---@class MsgData: unknown|vim.SystemCompleted
-------------------------------------------------

-------------------------------------------------
---@alias QfTypes "q"|"l"
-------------------------------------------------

-- TODO: @types
