require("colorizer").setup({
	-- filetypes = {
	-- 	"css",
	-- 	"html",
	-- 	"javascript",
	-- 	"javascriptreact",
	-- 	"json",
	-- 	"lua",
	-- 	"markdown",
	-- 	"markdown",
	-- 	"norg",
	-- 	"org",
	-- 	"pandoc",
	-- 	"scss",
	-- 	"txt",
	-- 	"typescript",
	-- 	"typescriptreact",
	-- 	"vim",
	-- 	"yaml",
	-- },
	user_default_options = {
		tailwind = "both",
		css = true,
		css_fn = true,
		names = false,
	},
})
