return {}
-- local capabilities = require("util.lsp_servers").capabilities()
--
-- local function fenced()
-- 	vim.g.markdown_fenced_languages = {
-- 		"ts=typescript",
-- 	}
-- end
--
-- return {
-- 	"sigmaSd/deno-nvim",
-- 	lazy = true,
--
-- 	dependencies = {
-- 		{ "neovim/nvim-lspconfig", lazy = true },
-- 		{ "nvim-treesitter/nvim-treesitter", lazy = true },
-- 	},
--
-- 	opts = {
-- 		server = {
-- 			-- on_attach = require("lspconfig.configs.denols").on_attach,
-- 			capabilities = capabilities,
-- 			settings = {
-- 				deno = {
-- 					inlayHints = {
-- 						parameterNames = {
-- 							enabled = "all",
-- 						},
-- 						parameterTypes = {
-- 							enabled = true,
-- 						},
--
-- 						variableTypes = {
-- 							enabled = true,
-- 						},
--
-- 						propertyDeclarationTypes = {
-- 							enabled = true,
-- 						},
--
-- 						functionLikeReturnTypes = {
-- 							enabled = true,
-- 						},
--
-- 						enumMemberValues = {
-- 							enabled = true,
-- 						},
-- 					},
-- 				},
-- 			},
-- 		},
-- 	},
--
-- 	setup = function(_, opts)
-- 		opts = opts or {}
-- 		require("deno-nvim").setup(opts)
-- 		fenced()
-- 	end,
-- }
