-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  { name = "suppress-event", match = { class = ".*" }, suppress_event = "maximize" },
}

-- You'll probably like this.
-- windowrule = suppressevent maximize,class:.*
