-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-blueman-manager",
    match = {
      class = "^(blueman-manager)$",
    },
    float = true,
    center = true,
    size = "1000 650",
  },
}

-- bluetooth blueman bluez
-- windowrule = float,class:^(blueman-manager)$
-- windowrule = size 1000 650,class:^(blueman-manager)$
