-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-media-players",
    match = {
      title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$",
    },
    float = true,
    size = "960 540",
    -- move = "25%-",
    move = {
      "monitor_w 25% - window_w / 2",
      "monitor_h 25% - window_h / 2",
    },
  },
}

-- windowrule = float,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
-- windowrule = size 960 540,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
-- windowrule = move 25%-,title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
