-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-pip-librewolf",
    match = {
      class = "^()$",
      title = "^(Picture-in-Picture)$",
    },
    float = true,
  },
  {
    name = "non-initial-focus-pip-librewolf",
    match = {
      title = "^(Picture-in-Picture):workspace$",
    },
    no_initial_focus = true,
  },
  {
    name = "float-pip-librewolf",
    match = {
      class = "^(LibreWolf)$",
      title = "^(Picture-in-Picture)$",
    },
    float = true,
  },
}

-- windowrule = float,class:^()$,title:^(Picture in picture)$"
-- windowrule = noinitialfocus,title:^(Picture-in-Picture):workspace
-- windowrule = float,class:^(LibreWolf)$,title:^(Picture-in-Picture)$
