-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-pavucontrol",
    match = {
      class = "^(org.pulseaudio.pavucontrol)$",
    },
    float = true,
    center = true,
    size = "1000 650",
  },
}

-- windowrule = float,class:^(org.pulseaudio.pavucontrol)$ # Make the volume mixer always float
-- windowrule = size 1000 650,class:^(org.pulseaudio.pavucontrol)$
