-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-qt5ct",
    match = {
      class = "^(qt5ct)$",
    },
    float = true,
    center = true,
    size = "960 540",
  },
}

-- windowrule = float,class:^(qt5ct)$
-- windowrule = size 960 540,class:^(qt5ct)$
