-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-appimagelauncher",
    match = {
      class = "^(AppImageLauncherSettings)$",
    },
    float = true,
    center = true,
    size = "1450 1000",
  },
}

-- windowrule = float,class:^(AppImageLauncherSettings)$
-- windowrule = size 1450 1000,class:^(AppImageLauncherSettings)$
