-- class: vivaldi-ndmlnoabbeafemnnijijgjkohaffjjnm-Default
-- title: Calendly - Scheduling - Event types - Scheduling - Calendly
-- initialClass: vivaldi-ndmlnoabbeafemnnijijgjkohaffjjnm-Default
-- initialTitle: Calendly - Scheduling

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "tag-vivaldi-calendly",
    match = {
      class = "^(vivaldi-.*-[dD]efault)$",
      initial_class = "^(vivaldi-.*-[dD]efault)$",
      title = "^([cC]alendly.*)$",
      initial_title = "^([cC]alendly.*)$",
    },
    tag = "+vivaldi_calendly",
  },

  -- Effects

  --# Float things
  {
    name = "float-tagged-vivaldi-calendly",
    match = {
      class = "^(vivaldi-.*-[dD]efault)$",
      tag = "vivaldi_calendly",
    },
    float = true,
    center = true,
    size = "1105 1150",
  },
}
