-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "tag-chromium",
    match = {
      class = "^([cC]hromium)$",
    },
    tag = "+chromium",
  },

  {
    name = "workspace-tagged-chromium",
    match = {
      tag = "chromium",
    },
    workspace = "1 silent",
    -- pseudo = true
    size = "2660 1300",
    persistent_size = true,
  },

  {
    name = "tag-chromium-devtools",
    match = {
      class = "^([cC]hromium)$",
      initial_title = "^(Devtools)$",
    },
    tag = "+chromiumDevtools",
  },

  {
    name = "float-tagged-chromium-devtools",
    match = {
      tag = "chromiumDevtools",
    },
    float = true,
    center = true,
    size = "2030 1060",
    persistent_size = true,
  },
}

-- windowrule = tag +chromiumDevtools,class:^(Chromium)$,initial-title:^(Devtools)$"
--
-- ## Dev tools
-- windowrule = float,tag:chromiumDevtools
-- # class:^(Chromium)$,initial-title:^(Devtools)$"
-- windowrule = persistentsize,tag:chromiumDevtools
-- # class:^(Chromium)$,initial-title:^(Devtools)$"
-- windowrule = size 2030 1060,tag:chromiumDevtools
-- # class:^(Chromium)$,initial-title:^(Devtools)$"

-- windowrule = tag +chromium,class:^([cC]hromium)$
--
-- # windowrule = opacity 1.0 override 1.0 override,class:^([cC]hromium)$
-- windowrule = workspace 1 silent,tag:chromium
-- # class:^([cC]hromium)$
-- windowrule = pseudo,tag:chromium
-- # class:^([cC]hromium)$
-- windowrule = size 2660 1300,tag:chromium
-- # class:^([cC]hromium)$
-- windowrule = persistentsize,tag:chromium
-- # class:^([cC]hromium)$
-- # allows spawning it via mod + b, without swapping
-- # windowrule = noinitialfocus,class:^([cC]hromium)$, # allows spawning it via mod + b, without swapping
