-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "opacity-code",
    match = {
      class = "^(code)$",
    },
    opacity = 1.00,
  },
}

-- windowrule = opacity 1.00,class:^(code)$
