-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "opacity-code",
    match = {
      class = "^(code)$",
    },
    opacity = "1.0 override 1.0 override",
  },
}

-- windowrule = opacity 1.00,class:^(code)$
