-- class: DaVinci Control Panels Setup
-- title: DaVinci Control Panels Setup
-- initialClass: DaVinci Control Panels Setup
-- initialTitle: DaVinci Control Panels Setup

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "tag-davinici-panels",
    match = {
      class = "^(DaVinci Control Panels Setup)$",
      initial_class = "^(DaVinci Control Panels Setup)$",
      title = "^(DaVinci Control Panels Setup)$",
      initial_title = "^(DaVinci Control Panels Setup)$",
    },
    tag = "+daviniciPanels",
  },

  -- Effects

  --# Generic opacity for tagged things
  {
    name = "tagged-davinici-panels",
    match = {
      tag = "daviniciPanels",
    },
    opacity = "1.0 override 1.0 override",
  },

  --# Float things
  {
    name = "float-tagged-davinici-panels",
    match = {
      tag = "daviniciPanels",
    },
    -- workspace = N silent
    float = true,
    center = true,
    size = "1280 720",
    -- opacity = 1.0 override 1.0 override
  },
}

--# Other options/effects
-- border_size = 0
