-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "workspace-docker-desktop",
    match = {
      class = "^(Docker Desktop)$",
    },
    workspace = "7 silent",
    no_initial_focus = true,
  },
}

-- class: Docker Desktop
-- title: Images - Docker Desktop
-- initialClass: Docker Desktop
-- initialTitle: Docker Desktop

-- windowrule = workspace 8,class:^(Docker Desktop)$
