--#################################################
--## REMBMER TO INCLUDE!! ###
--#################################################
--
--########################
--## Get the window via ###
-- `"sleep 3; hyprctl activewindow"`
--## Paste info at top of file ###
--########################
--

-- Window 56347f40ad80 -> feh [1 of 1] - <some path>
-- 	mapped: 1
-- 	hidden: 0
-- 	at: 2565,45
-- 	size: 2204,1390
-- 	workspace: 3 (3)
-- 	floating: 0
-- 	monitor: 0
-- 	class: feh
-- 	title: feh [1 of 1] - <some path>
-- 	initialClass: feh
-- 	initialTitle: feh [1 of 1] - <some path>

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "tag-feh",
    match = {
      class = "^(feh)$",
    },
    tag = "+feh",
  },

  --# Float things
  {
    name = "float-tagged-feh",
    match = {
      class = "^(feh)$",
      tag = "feh",
    },
    float = true,
    -- move = 90 95
    center = true,
    -- size = 1280 720
  },
}
