-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-keepass",
    match = {
      class = "^(org.keepassxc.KeePassXC)$",
    },
    float = true,
    center = true,
    size = "1450 1000",
  },

  {
    name = "focus-keepass",
    match = {
      class = "^(org.keepassxc.KeePassXC)$",
      initial_title = "^(Unlock Database - KeePassXC)$",
    },
    -- initialTitle: Unlock Database - KeePassXC
    focus_on_activate = true,
    -- no_initial_focus = false
  },
}

-- keepass pass keyring

-- windowrule = float,class:^(org.keepassxc.KeePassXC)$
-- windowrule = size 1450 1000,class:^(org.keepassxc.KeePassXC)$
