-- class: kitty
-- title: ~
-- initialClass: kitty
-- initialTitle: kitty
-- Tagging

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-kitty",
    match = {
      class = "^(kitty)$",
      initial_class = "^(kitty)$",
      initial_title = "^(kitty)$",
    },
    tag = "+kitty",
  },

  -- Effects

  --# Float things
  {
    name = "float-tagged-kitty",
    match = {
      tag = "kitty",
    },
    float = true,
    center = true,
    size = "1280 720",
  },

  {
    name = "float-tagged-no-border",
    match = {
      tag = "kitty",
      float = true,
    },
    border_size = 0,
  },
}
