-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-polychromatic",
    match = {
      class = "^(polychromatic)$",
    },
    tag = "+polychromatic",
  },

  {
    name = "float-tagged-polychromatic",
    match = {
      tag = "polychromatic",
    },
    float = true,
    center = true,
    size = "1050 950",
  },

  {
    name = "size-polychromatic-device-info",
    match = {
      class = "^(polychromatic)$",
      title = "^(Device Information - .+)$",
    },
    size = "200 400",
  },
}

-- Razer / mouse / polychromatic

-- class: polychromatic
-- title: Device Information - Razer Viper V2 Pro (Wired)
-- initialClass: polychromatic
-- initialTitle: Device Information - Razer Viper V2 Pro (Wired)

-- windowrule = tag +polychromatic,class:^polychromatic$
-- windowrule = float,tag:polychromatic
-- windowrule = size 1050 950,tag:polychromatic
-- windowrule = size 200 400, class:^polychromatic$, initial-title:^Device Information - .+$
