-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "float-qBittorrent-torrent",
    match = {
      class = "^(org.qbittorrent.qBittorrent)$",
    },
    tag = "+torrent",
  },

  {
    name = "float-qBittorrent-torrent-window",
    match = {
      tag = "torrent",
      initial_title = "^[(^qBittorrent v.*)]$",
    },
    float = true,
    persistent_size = true,
  },
}

-- windowrule = tag +torrent,class:^org.qbittorrent.qBittorrent$
-- windowrule = float, tag:torrent,initial-title:^[(^qBittorrent v.*)]$
-- windowrule = persistentsize,tag:torrent
