-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "float-solaar",
    match = {
      class = "^(solaar)$",
      title = "^(Solaar)$",
    },
    float = true,
    center = true,
    size = "1000 650",
  },

  {
    name = "float-solaar-rule-editor",
    match = {
      class = "^(solaar)$",
      title = "^(Solaar Rule Editor)$",
    },
    float = true,
    center = true,
    size = "600 500",
  },
}

-- Logitech logi controller

-- windowrule = float,class:^(solaar)$
-- windowrule = size 1000 650,class:^(solaar)$,title:^(Solaar)$
-- windowrule = size 600 500,class:^(solaar)$,title:^(Solaar Rule Editor)$
