-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {

  {
    name = "workspace-spotify",
    match = {
      class = "^([sS]potify)$",
    },
    workspace = "8 silent",
    maximize = true,
    -- border_size = 0
    -- float = true
    -- center = true
    -- size = 1200 800
  },
}

-- Spotify

-- windowrule = workspace 9,class:^([sS]potify)$
-- windowrule = float,class:^([sS]potify)$
-- windowrule = center,class:^([sS]potify)$
