-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {
  {
    name = "tag-steam-updater",
    match = {
      title = "^(Steam - Self Updater)$",
    },
    tag = "+steamUpdater",
  },

  {
    name = "float-tagged-steam-updater",
    match = {
      class = "^()$",
      tag = "steamUpdater",
    },
    workspace = "4 silent",
    float = true,
    no_initial_focus = true,
    no_blur = true,
  },

  -- Tagging
  {
    name = "tag-steam-signin",
    match = {
      class = "^([sS]team)$",
      title = "^(Sign in to [sS]team)$",
    },
    tag = "+steamSignIn",
  },

  {
    name = "no-initial-focus-tagged-steam-signin",
    match = {
      tag = "steamSignIn",
    },
    workspace = "4 silent",
    no_initial_focus = true,
    float = true,
    center = true,
    no_blur = true,
    size = "850 720",
  },

  -- Tagging
  {
    name = "tag-steam-main",
    match = {
      class = "^([sS]team)$",
      title = "^([sS]team)$",
    },
    tag = "+steamMain",
  },

  {
    name = "tagged-steam-main",
    match = {
      tag = "steamMain",
    },
    workspace = "4 silent",
    opacity = "1.0 override 1.0 override",
    no_blur = true,
    border_size = 0,
  },

  -- Tagging
  {
    name = "tag-steam-settings",
    match = {
      class = "^([sS]team)$",
      title = "^([sS]team [sS]ettings)$",
    },
    tag = "+steamSettings",
  },

  {
    name = "tagged-steam-settings",
    match = {
      tag = "steamSettings",
    },
    workspace = "4 silent",
    opacity = "1.0 override 1.0 override",
    float = true,
    no_blur = true,
    size = "850 720",
  },

  {
    name = "tag-steam-special-offers",
    match = {
      class = "^([sS]team)$",
      title = "^(Special Offers)$",
    },
    tag = "+steamSpecialOffers",
  },

  {
    name = "tagged-steam-special-offers",
    match = {
      tag = "steamSpecialOffers",
    },
    workspace = "4 silent",
    float = true,
    no_blur = true,
  },
}

-- class: steam
-- title: Special Offers
-- initialClass: steam
-- initialTitle: Special Offers

--############
--## Steam ###
--############

--## windowrule = workspace 4 silent,class:^([sS]team)$

--## windowrule = tag +steamUpdater,title:^(Steam - Self Updater)$
--## windowrule = float,class:^()$,tag:steamUpdater
--## windowrule = noinitialfocus,tag:steamUpdater
-- title:^(Steam - Self Updater)$

-- class: steam
-- title: Sign in to Steam
-- initialClass: steam
-- initialTitle: Sign in to Steam
--## windowrule = noinitialfocus,class:^([sS]team)$,title:^(Sign in to [sS]team)$

--## windowrule = opacity 1.0 override 1.0,class:^([sS]team)$,title:^([sS]team)$

--## windowrule = size 2400 1250,title:^([sS]team)$  #class:^([sS]team)$

--## windowrule = opacity 1.0 override 1.0,class:^([sS]team)$,title:^([sS]team [sS]ettings)$
--## windowrule = float,title:^([sS]team [sS]ettings)$,
--## windowrule = size 850 720,title:^([sS]team [sS]ettings)$

--## windowrule = center,title:^([sS]ign in to [sS]team)$
--## windowrule = size 850 720,title:^([sS]ign in to [sS]team)$

-- TODO: need to pin the friends list as well

-- windowrule = tag +steamClass,class:^([sS]team)$
-- windowrule = workspace 4,tag:steamClass
-- windowrule = stayfocused,tag:steamClass
--
-- windowrule = tag +steamTitle,title:^[sS]team.-.[sS].*$
-- # windowrule = tag +steamTitle,title:^[sS]team(\s?|.?)?(.-.[sS])?.*$
-- windowrule = stayfocused,tag:steamTitle
--
-- # class:^([sS]team)$
--
-- windowrule = float,class:^()$,tag:steamTitle
-- # title:^(Steam - Self Updater)$
--
-- windowrule = opacity 1.0 override 1.0,tag:steamClass
-- # class:^([sS]team)$,title:^([sS]team)$
-- # windowrule = float,title:^([sS]team)$
-- # windowrule = float,class:^([sS]team)$
--
-- windowrule = size 2400 1250,title:^([sS]team)$  #class:^([sS]team)$
--
-- windowrule = opacity 1.0 override 1.0,tag:steamTitle
-- # ,class:^([sS]team)$,title:^([sS]team [sS]ettings)$
-- windowrule = float,title:^([sS]team [sS]ettings)$,
-- windowrule = size 850 720,title:^([sS]team [sS]ettings)$
--
-- windowrule = center,title:^([sS]ign in to [sS]team)$
-- windowrule = size 850 720,title:^([sS]ign in to [sS]team)$

--################
--## Steam END ###
--################
