-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "float-swappy",
    match = {
      class = "^(swappy)$",
    },
    float = true,
    center = true,
    size = "2560 1200",
  },
}

-- you cannot scale swappy lol
-- windowrule = float,class:^(swappy)$
-- windowrule = size 2560 1200,class:^(swappy)$
