--# Writing window
-- class: org.mozilla.Thunderbird
-- title: Write: (no subject) - Thunderbird
-- initialClass: org.mozilla.Thunderbird
-- initialTitle: Write: (no subject)

--# Client window
-- class: org.mozilla.Thunderbird
-- title: Spam - <account@domain.com> - Mozilla Thunderbird
-- initialClass: org.mozilla.Thunderbird
-- initialTitle: Mozilla Thunderbird

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-thunderbird-write",
    match = {
      class = "^(org.mozilla.Thunderbird)$",
      title = "^(Write:\\s.*)$",
    },
    -- match:initial_class = ^(STUFF)$
    -- match:initial_title = ^(MORE_STUFF)$
    tag = "+thunderbird-write",
  },

  -- Tagging - Client windows
  {
    name = "tag-workspace-thunderbird",
    match = {
      class = "^(org.mozilla.Thunderbird)$",
      initial_title = "^(Mozilla\\sThunderbird)$",
    },
    -- match:initial_class = ^(STUFF)$
    -- match:initial_title = ^(MORE_STUFF)$
    tag = "+thunderbird-workspace",
  },

  -- Effects

  --# Generic opacity for tagged things
  {
    name = "tagged-thunderbird-write",
    match = {
      tag = "thunderbird-write",
    },
    opacity = "1.0 override 1.0 override",
    persistent_size = true,
  },

  {
    name = "workspace-thunderbird",
    match = {
      tag = "thunderbird-workspace",
    },
    workspace = "3 silent",
  },

  --# Float things
  {
    name = "float-tagged-thunderbird-write",
    match = {
      tag = "thunderbird-write",
    },
    -- workspace = N silent
    float = true,
    center = true,
    size = "1600 900",
  },
}
