-- class: ueberzugpp_ugl8tu3qkn
-- title: ueberzugpp_ugl8tu3qkn
-- initialClass: ueberzugpp_ugl8tu3qkn
-- initialTitle: ueberzugpp_ugl8tu3qkn
-- pid: 112967

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {
  {
    name = "tag-ueberzugpp",
    match = {
      class = "^(ueberzugpp_.*)$",
      initial_class = "^(ueberzugpp_.*)$",
      title = "^(ueberzugpp_.*)$",
      initial_title = "^(ueberzugpp_.*)$",
    },
    tag = "+ueberzugpp_nvim",
  },

  -- Effects

  --# Generic opacity for tagged things
  -- windowrule {
  --   name = tagged-THING
  --   match:tag = THE_TAG
  -- opacity = 1.0 override 1.0 override
  --   persistent_size = true
  -- }

  --# Float things
  {
    name = "float-tagged-ueberzugpp",
    match = {
      tag = "ueberzugpp_nvim",
    },
    -- workspace = N silent
    -- center = true
    opacity = "1.0 override 1.0 override",
    -- float = true
    -- size = 1280 720
    -- move = 45 95
  },

  --# NO INITIAL FOCUS
  {
    name = "no-initial-focus-tagged-ueberzugpp",
    match = {
      tag = "ueberzugpp_nvim",
    },
    no_initial_focus = true,
    persistent_size = true,
    -- float = true
    -- center = true
    -- size = X_POS Y_POS
  },
}

--# Other options/effects
-- border_size = 0
