-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-vivaldi-init-class",
    match = {
      initial_class = "^([vV]ivaldi)(-+)(stable?)$",
    },
    tag = "+vbrowserInitClass",
  },

  -- Tagging
  {
    name = "tag-vivaldi-init-title",
    match = {
      initial_title = "^([vV]ivaldi(\\s+)(-)(\\s+)[vV]ivaldi)$",
    },
    tag = "+vbrowserInitTitle",
  },

  {
    name = "workspace-tagged-vivaldi",
    match = {
      tag = "vbrowserInitTitle",
    },
    workspace = "1 silent",
  },

  {
    name = "workspace-tagged-vivaldi",
    match = {
      tag = "vbrowserInitClass",
    },
    workspace = "1 silent",
  },

  {
    name = "opacity-tagged-vivaldi",
    match = {
      tag = "vbrowserInitClass",
    },
    opacity = "1.0 override 1.0 override",
    opaque = true,
  },

  {
    name = "opacity-tagged-vivaldi",
    match = {
      tag = "vbrowserInitTitle",
    },
    opacity = "1.0 override 1.0 override",
    opaque = true,
  },

  -- Tagging
  {
    name = "tag-vivaldi-settings",
    match = {
      title = "^([vV]ivaldi)(\\s)(Settings\\:)(.*)(-\\s)?([vV]ivaldi)?$",
    },
    tag = "+vSettingsInitTitle",
  },

  {
    name = "opacity-tagged-vivaldi-settings",
    match = {
      tag = "vSettingsInitTitle",
    },
    opacity = "1.0 override 1.0 override",
    opaque = true,
  },

  {
    name = "float-tagged-vivaldi-settings",
    match = {
      tag = "vSettingsInitTitle",
    },
    float = true,
    center = true,
    size = "1200 1100",
    persistent_size = true,
  },

  -- Tagging
  {
    name = "tag-vivaldi-webapp",
    match = {
      class = "^([vV]ivaldi)(-?)+(.*)(-?)+([dD]efault)$",
      tag = "vbrowserInitTitle",
    },
    tag = "+vwebapp-general",
  },

  {
    name = "float-tagged-vivaldi-webapp",
    match = {
      tag = "vwebapp-general",
    },
    -- pseudo = true
    float = true,
    persistent_size = true,
    opaque = true,
  },
}

-- Vivaldi
