-- class: vivaldi-ggjocahimgaohmigbfhghnlfcnjemagj-Default
-- title: Grok
-- initialClass: vivaldi-ggjocahimgaohmigbfhghnlfcnjemagj-Default
-- initialTitle: Grok

-- vivaldi / web app / webapp / default

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

return {

  {
    name = "tag-vivaldi-webapp-grok",
    match = {
      class = "^([vV]ivaldi)(-)(.*)(-)([dD]efault)$",
      initial_class = "^([vV]ivaldi)(-)(.*)(-)([dD]efault)$",
      title = "^([gG]rok)$",
      initial_title = "^([gG]rok)$",
    },
    -- match:class = ^([vV]ivaldi-?)(.*)(-+)(-?[dD]efault)$
    tag = "+vwebapp-grok",
  },

  {
    name = "vivaldi-webapp-grok",
    match = {
      tag = "vwebapp-grok",
    },
    size = "1000 1300",
    move = "20 95",
    pseudo = false,
    float = false,
    persistent_size = true,
    -- opaque = vwebapp-grok
    -- opacity = 1.0 override 1.0 override
  },
}

-- Vivaldi webapp grok / WebApp / Webapp / web app / Web App / Grok / grok
