-- at: 1725,220
-- size: 1669,1047
-- class: xdg-desktop-portal-gtk
-- title: All Files
-- initialClass: xdg-desktop-portal-gtk
-- initialTitle: All Files

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-xdg-portal-gtk",
    match = {
      class = "^(xdg-desktop-portal-gtk)$",
      initial_class = "^(xdg-desktop-portal-gtk)$",
    },
    tag = "+portal_xdg",
  },

  -- Effects

  --# Generic opacity for tagged things
  -- windowrule {
  --   name = tagged-THING
  --   match:tag = THE_TAG
  --   opacity = 1.0 override 1.0 override
  --   persistent_size = true
  -- }

  --# Float things
  {
    name = "float-tagged-portal_xdg",
    match = {
      tag = "portal_xdg",
    },
    float = true,
    center = true,
    size = "1680 1080",
    -- opacity = 1.0 override 1.0 override
  },
}
