-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-ytm",
    match = {
      class = "^com.github.th_ch.youtube.+$",
    },
    tag = "+ytm",
  },

  {
    name = "workspace-ytm",
    match = {
      tag = "ytm",
    },
    workspace = "8 silent",
  },

  {
    name = "float-ytm",
    match = {
      tag = "ytm",
    },
    -- float = true
    center = true,
    size = "1250 850",
    persistent_size = true,
    maximize = true,
  },
}
