-- class: org.pwmt.zathura
-- title: /home/dwarf/Documents/GitHub_Projects/Typst/typst_resume/Resume.pdf
-- initialClass: org.pwmt.zathura
-- initialTitle: /home/dwarf/Documents/GitHub_Projects/Typst/typst_resume/Resume.pdf

-- Tagging
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
return {

  {
    name = "tag-zathura",
    match = {
      class = "^(org.pwmt.zathura)$",
    },
    -- match:initial_title = ^(org.pwmt.zathura)$
    tag = "+zathura",
  },

  -- Effects

  --# Generic opacity for tagged things
  {
    name = "tagged-zathura-generic",
    match = {
      tag = "zathura",
    },
    opacity = "1.0 override 1.0 override",
    persistent_size = true,
  },

  --# Float things
  {
    name = "float-tagged-zathura",
    match = {
      class = "^(org.pwmt.zathura)$",
      tag = "zathura",
    },
    float = true,
    -- opacity = 1.0 override 1.0 override
    -- center = true
    size = "1100 1300",
  },
}

--# NO INITIAL FOCUS
-- windowrule {
--   name = no-initial-focus-tagged-THING
--   match:class = ^(STUFF)$
--   match:tag = THE_TAG
--   no_initial_focus = true
--   float = true
--   center = true
--   size = X_POS Y_POS
-- }

--# Other options/effects
-- border_size = 0
