-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
  name = "float-zmk-studio",
  match = {
    class = "^(zmk-studio)$",
  },
  float = true,
  center = true,
  size = "1450 1000",
})

-- ZMK Studio / zmk-studio / zmk

--## windowrule = float,class:^(zmk-studio)$
--## windowrule = size 1450 1000,class:^(zmk-studio)$
