[options]
# AurOnly
SortBy=votes

# I think we'll keep this on lol
# SkipReview

# Skipping check step & deps
# NoCheck

# Exit early/first package build failure
FailFast

# Update 'devel' packages
Devel
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
