# theme = "jetbrains_dark"
# theme = "github_dark_dimmed"
# theme = "jellybeans"
# theme = "modus_vivendi_tinted"
# theme = "peachpuff"
# theme = "kaolin-dark"

# theme = "doom-one"
# theme = "kanagawa"

# theme = "rose_pine"
# theme = "ayu_dark"

# theme = "github_dark"
# theme = "material_darker" ### Good.
# theme = "lapis_aquamarine"
# theme = "material_deep_ocean"
# theme = "focus_nova"
# theme = "term16_dark"

theme = "material_palenight"

# theme = "tokyonight"
# theme = "tokyonight_moon"
# theme = "tokyonight_storm"
# theme = "rose_pine_moon"


[editor]
line-number = "relative"
scrolloff = 4
cursorline = true
bufferline = "multiple"

clipboard-provider = "x-sel"

completion-trigger-len = 1
auto-info = true
# rulers = [90, 120]
color-modes = true
popup-border = "all"

end-of-line-diagnostics = "hint"


[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline


# [editor.clipboard-provider.custom]

# yank = { command = "wl-copy", args = ["-n"] }
# paste = { command = "wl-paste", args = ["-n"] }
# primary-yank = { command = "wl-copy", args = ["-n"] }
# primary-paste = { command = "wl-paste", args = ["-n"] }


[editor.gutters]
layout = ["spacer", "diagnostics", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 3

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"


[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
# center = [""]
right = [
  "diagnostics",
  "primary-selection-length",
  "position",
  "total-line-numbers",
  "spacer",
  "position-percentage",
  "spacer",
  "spinner",
  "spacer",
]

separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
max-depth = 4
hidden = false
follow-symlinks = true
git-ignore = true
git-global = true
ignore = true


[editor.indent-guides]
render = true
character = "▏"
skip-levels = 0


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
# '<' = '>'


[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true


[editor.whitespace.render]
tab = "all"
# space = "all"
nbsp = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"

####################


[keys.normal.space]
"." = ":config-reload"

"n" = "goto_next_buffer"
"p" = "goto_previous_buffer"


F = "no_op"


[keys.normal.space.f] # Find 
f = "file_picker_in_current_directory"
F = "file_picker"
b = "buffer_picker"
p = "workspace_diagnostics_picker"
P = "diagnostics_picker"
l = "last_picker"
j = "jumplist_picker"
w = "global_search"


[keys.normal.space.l] # LSP
f = ":format"
a = "code_action"

r = "select_references_to_symbol_under_cursor"
R = "rename_symbol"
s = "symbol_picker"
S = "workspace_symbol_picker"

d = "diagnostics_picker"
D = "workspace_diagnostics_picker"

h = ":tree-sitter-subtree"
t = ":tree-sitter-highlight-name"


[keys.normal.space.w] # Window
left = "no_op"
right = "no_op"
up = "no_op"
down = "no_op"

# C-h = "no_op"
# C-j = "no_op"
# C-k = "no_op"
# C-l = "no_op"

H = "no_op"
L = "no_op"
J = "no_op"
K = "no_op"


[keys.normal.space.w.w] # Window

h = "swap_view_left"
j = "swap_view_down"
k = "swap_view_up"
l = "swap_view_right"


[keys.normal.space.b] # Buffers

x = ":buffer-close"
d = ":buffer-close"

n = "goto_next_buffer"
p = "goto_previous_buffer"
o = ":buffer-close-others"

[keys.normal]

C-e = ["scroll_down"]
C-y = ["scroll_up"]
K = "hover"
C-s = ":w"              # Saving with Ctrl+s
C-g = ":show-directory"

# Centering viewport on page scrolling
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]


"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"


# TODO: 
# C = [
#   "extend_to_line_end",
#   "yank_main_selection_to_clipboard",
#   "delete_selection",
#   "insert_mode",
# ]
C = ["extend_to_line_end", "evil_delete_immediate", "insert_mode"]


## TODO:
# D = [
#   "extend_to_line_end",
#   "yank_main_selection_to_clipboard",
#   "delete_selection",
# ]

D = ["extend_to_line_end", "evil_delete_immediate"]

# S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable


# p = ["paste_clipboard_after", "collapse_selection"]
# P = ["paste_clipboard_before", "collapse_selection"]

## TODO:
# Would be nice to add ya and yi, but the surround commands can't be chained


## TODO: 
# pressing 'a' enters insert mode, however 
# when exiting, the cursor moves forward by one char
# in vim this 'snaps backwards' to the char you had started on

# a = ["append_mode", "collapse_selection"]


u = ["undo", "collapse_selection"]
C-r = ["redo"]


# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]


[keys.normal.d]
d = ["extend_to_line_bounds", "evil_delete_immediate"]

i = ["select_textobject_inner"]

## TODO: pairs not being handled properly really (? ie: da( doesn't work as inended, nor does da"  etc. )
a = ["select_textobject_around", "evil_delete"]

G = [
  #
  "extend_to_line_bounds",
  "extend_to_file_end",
  "evil_delete_immediate",
]

## TODO: 
# t = ["extend_till_char", "yank_main_selection_to_clipboard", "delete_selection"]

L = ["extend_to_line_end", "evil_delete_immediate"]

H = ["extend_to_line_start", "evil_delete_immediate"]

###########################


[keys.normal.y]

# L = ["select_mode", "extend_to_line_end", "yank_to_clipboard", "normal_mode"]
#
# H = [
#   "select_mode",
#   "goto_line_start",
#   "yank_main_selection_to_clipboard",
#   "collapse_selection",
#   "normal_mode",
# ]


[keys.normal.g]
c = { c = "toggle_comments" }


[keys.insert]
# Escape the madness! No more fighting the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]


[keys.insert.j]
# j = "normal_mode"
k = "normal_mode"

[keys.insert.k]
j = "normal_mode"
# k = "normal_mode"


[keys.select]


"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"


## TODO: These are doing move->start selection (not selection-move)
# G = "goto_file_end"
G = ["collapse_selection", "select_mode", "goto_file_end"]


c = ["delete_selection", "insert_mode"]


# p = "replace_selections_with_clipboard" # No life without this
# P = "paste_clipboard_before"


[keys.select.g]
# c = { c = "toggle_comments" }

c = "toggle_comments"
