[v1]
"bacon 3.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"cargo-binstall 1.15.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-expand 1.0.118 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.23.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-insta 1.43.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-insta"]
"cargo-llvm-cov 0.6.21 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-llvm-cov"]
"cargo-machete 0.9.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-machete"]
"cargo-nextest 0.9.111 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-udeps 0.1.60 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 18.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-workspaces 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"create-tauri-app 4.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-create-tauri-app"]
"flamegraph 0.6.9 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"gumbo 0.1.24 (registry+https://github.com/rust-lang/crates.io-index)" = ["gumbo"]
"just 1.43.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"knope 0.21.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["knope"]
"loco 0.16.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["loco"]
"spider_cli 2.37.169 (registry+https://github.com/rust-lang/crates.io-index)" = ["spider"]
"tauri-cli 2.9.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
