## command aliases
[alias]
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
br = "build --release"
cl = "clean"
clipa = "clippy --all-targets --all-features -- -D warnings"
clipP = "clippy -- -W clippy::pedantic"

## Other alias examples from docs
# recursive_example = "rr --example recursions"
# space_example = ["run", "--release", "--", "\"command list\""]

# ensure that rust is installed WITHIN the msys2 environment
# ensure that the CORRECT verison of msys2 is at the top of path.
# This should be fine if you're using clang64 for c/c++ too.
[target.x86_64-pc-windows-gnu]
linker = "C:\\Users\\<< YOUR USERNAME >>\\scoop\\apps\\msys2\\current\\clang64\\bin\\gcc.exe"
ar = "C:\\Users\\<< YOUR USERNAME >>\\scoop\\apps\\msys2\\current\\clang64\\bin\\ar.exe"
