## Empty values are used to reset config keys to default.
# key =


# keybind = ctrl+a>g+g=scroll_to_top
# gtk-toolbar-style = flat

# only works on macos
keybind = global:super+grave_accent=toggle_quick_terminal

# Remove the ctrl+enter fullscreen bind - let WM handle it
keybind = ctrl+enter=unbind
keybind = ctrl+,=unbind

# keybind = ctrl+shift+e=new_split:down

# keybind = ctrl+a>ctrl+a=goto_tab:previous
# keybind = ctrl+a>c=new_tab

keybind = alt+t=new_tab
keybind = alt+q=close_surface
keybind = alt+shift+d=close_surface

# Split horizontal
keybind = ctrl+shift+e=unbind
keybind = ctrl+shift+-=new_split:down
keybind = alt+-=new_split:down

# Split vertical
keybind = ctrl+shift+o=unbind
keybind = ctrl+shift+|=new_split:right
keybind = alt+\=new_split:right


# keybind = ctrl+alt+arrow_up=goto_split:up
# keybind = ctrl+alt+arrow_down=goto_split:down
# keybind = ctrl+alt+arrow_left=goto_split:left
# keybind = ctrl+alt+arrow_right=goto_split:right

keybind = alt+h=goto_split:left
keybind = alt+j=goto_split:down
keybind = alt+k=goto_split:up
keybind = alt+l=goto_split:right


keybind = ctrl+alt+,=open_config

keybind = ctrl+shift+r=reload_config
keybind = ctrl+\=reload_config
keybind = ctrl+shift+comma=reload_config

keybind = alt+arrow_up=scroll_page_up
keybind = alt+arrow_down=scroll_page_down

keybind = alt+shift+arrow_up=resize_split:up,50
keybind = alt+shift+arrow_down=resize_split:down,50
keybind = alt+shift+arrow_left=resize_split:left,50
keybind = alt+shift+arrow_right=resize_split:right,50

keybind = alt+u=scroll_page_up
keybind = alt+d=scroll_page_down

keybind = alt+comma=move_tab:-1
keybind = alt+period=move_tab:+1

keybind = alt+n=next_tab
keybind = alt+p=previous_tab

# keybind = ctrl+comma=open_config
# keybind = ctrl+a>c=new_tab
# keybind = ctrl+a>equal=equalize_splits
# keybind = ctrl+a>d=close_tab
# keybind = ctrl+a>$=last_tab
#
# keybind = ctrl+a>h=goto_split:left
# keybind = ctrl+a>j=goto_split:down
# keybind = ctrl+a>k=goto_split:up
# keybind = ctrl+a>l=goto_split:right
# keybind = ctrl+a>pipe=new_split:right
#
# keybind = ctrl+a>z=toggle_split_zoom
# keybind = ctrl+a>minus=new_split:down
# keybind = ctrl+a>i=new_split:right
#
# keybind = ctrl+left=resize_split:left,10
# keybind = ctrl+up=resize_split:up,10
#
# keybind = ctrl+a>v>j=scroll_page_down
# keybind = ctrl+a>v>k=scroll_page_up
#
# keybind = ctrl+a>g>g=scroll_to_top
#
#
#
#
#
# keybind = ctrl+a>shift+d=close_window
# keybind = ctrl+shift+c=copy_to_clipboard
#
#
# keybind = ctrl+physical:one=goto_tab:1
# keybind = ctrl+physical:two=goto_tab:2
# keybind = ctrl+physical:three=goto_tab:3
# keybind = ctrl+physical:four=goto_tab:4
# keybind = ctrl+physical:five=goto_tab:5
# keybind = ctrl+physical:six=goto_tab:6
# keybind = ctrl+physical:seven=goto_tab:7
# keybind = ctrl+physical:eight=goto_tab:8
# keybind = ctrl+physical:nine=goto_tab:9
