# vim: set ft=conf syntax=conf:

#########################
## Darwin 'specific'  ##
#########################


## Unbinds

keybind = cmd+,=unbind
# Handled on darwin/macos via cmd+shift+n !
keybind = cmd+n=unbind


keybind = ctrl+shift+r=unbind
keybind = ctrl+\=unbind
keybind = ctrl+shift+comma=unbind


keybind = cmd+shift+n=new_window
keybind = cmd+shift+r=reload_config
