# ONLY FOR TESTING, default to true normally,
# which will only animate the ACTIVE window,
# not ALL of them (which is what always does)
#
# However - if you leave as always, even if it's not active/focused, 
# it will play the shader animation anyway. (Which can be cool for some shaders)
custom-shader-animation = always

###############
### Shaders ###
###############

# ./ghostty-shaders/

# custom-shader = ./ghostty-shaders/glitchy.glsl
# custom-shader = ./ghostty-shaders/water.glsl
# custom-shader = ./ghostty-shaders/tft.glsl

# custom-shader = ./ghostty-shaders/bettercrt.glsl
# custom-shader = ./ghostty-shaders/bloom.glsl


# This is really cool - gives the old-school ghosting effect crt monitors had!
# custom-shader = ./ghostty-shaders/in-game-crt.glsl

# custom-shader = ./ghostty-shaders/cineShader-Lava.glsl

# Basically the best of all of the 'look OG' styles
# custom-shader = ./ghostty-shaders/glow-rgbsplit-twitchy.glsl
# custom-shader = ./ghostty-shaders/glow-rgbsplit-twitchy.glsl
# Combine with this for a LOT of eye-sting
# custom-shader = ./ghostty-shaders/bloom.glsl


# custom-shader = ./ghostty-shaders/matrix-hallway.glsl

# This is dope, but somewhat 'needs' the bloom
# custom-shader = ./ghostty-shaders/retro-terminal.glsl
# custom-shader = ./ghostty-shaders/bloom.glsl


# custom-shader = ./ghostty-shaders/sparks-from-fire.glsl

# custom-shader = ./ghostty-shaders/starfield-colors.glsl

# Possible to do it only when it's inactive?
# custom-shader = ./ghostty-shaders/underwater.glsl

# custom-shader = ./ghostty-shaders/cubes.glsl

