# hyprland-qt-support provides a QML style for hypr* qt6 apps.

# int [ 0 .. 3 ]
# Default is 1
roundness = 1

# int [ 0 .. 3 ]
# Default is 1
border_width = 0

# Default is: false
reduce_motion = false

