#######################################################
### Hyprpaper v0.8+ config (hyprtoolkit)            ###
### Use IPC or wallust template to manage            ###
#######################################################

ipc = true
splash = true

wallpaper {
    monitor = *
    path = /home/dwarf/Pictures/wallpapers/wallhaven-anime-girl_at_drink_fridge.jpg
    fit_mode = cover
}
