#########################
$hyprdir = $HOME/.config/hypr
$rules_dir = $hyprdir/configs/rules

source = $hyprdir/configs/programs.conf
#########################

#########################
# important
# source = $hyprdir/configs/env.conf # re-enable if NOT using uwsm to manage hyprland launchng

source = $hyprdir/hypr-colors.conf
source = $hyprdir/configs/monitor.conf
# source = $hyprdir/configs/binds.conf ## old
source = $hyprdir/configs/keymaps.conf
# source = $hyprdir/configs/rules.conf
source = $rules_dir/01_init.conf

#########################

source = $hyprdir/configs/visualfeel.conf
source = $hyprdir/configs/execs.conf
source = $hyprdir/configs/input.conf
source = $hyprdir/configs/group.conf
source = $hyprdir/configs/misc.conf

source = $hyprdir/configs/layouts.conf
#########################
#########################


# Binds
# https://wiki.hypr.land/Configuring/Variables/#binds
binds {
    pass_mouse_when_bound = false
    scroll_event_delay = 200
    workspace_back_and_forth = true
    hide_special_on_workspace_change = false
    allow_workspace_cycles = true
    workspace_center_on = 1                                # 0 is center, 1 is last active window of that workspace
    focus_preferred_method = 0                             # 0 - history, 1 - length
    ignore_group_lock = false
    movefocus_cycles_fullscreen = false
    movefocus_cycles_groupfirst = false
    disable_keybind_grabbing = false                       # if enabled, apps requesting (eg: VM's) won't be able to do so
    window_direction_monitor_fallback = true
    allow_pin_fullscreen = false
    drag_threshold = 0
}

xwayland {
    enabled = true
    use_nearest_neighbor = true
    force_zero_scaling = true
    create_abstract_socket = false
}

opengl {
    nvidia_anti_flicker = true
}

render {
    direct_scanout = 2                                     # 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
    expand_undersized_textures = true
    xp_mode = false
    ctm_animation = 2                                      #2 means “auto” which disables them on Nvidia.
    cm_enabled = true                                      #requires restart
    cm_fs_passthrough = 2                                  #0 - off, 1 - always, 2 - hdr only
    send_content_type = true
    cm_auto_hdr = 1                                        # Auto-switch to HDR in fullscreen when needed. 0 - off, 1 - switch to cm, hdr, 2 - switch to cm, hdredid
    new_render_scheduling = false
}

cursor {
    sync_gsettings_theme = true
    no_hardware_cursors = 2
    no_break_fs_vrr = 2
    min_refresh_rate = 24
    hotspot_padding = 1
    inactive_timeout = 0
    no_warps = false
    persistent_warps = false
    warp_on_change_workspace = 1
    warp_on_toggle_special = 0
    default_monitor = "DP-1"
    zoom_factor = 1.0
    zoom_rigid = false
    enable_hyprcursor = true
    hide_on_key_press = true
    hide_on_touch = true
    use_cpu_buffer = 2
    warp_back_after_non_mouse_input = false
}

ecosystem {
    no_update_news = false
    no_donation_nag = true
    enforce_permissions = false
}

experimental {
  xx_color_management_v4 = true
}

debug {
    full_cm_proto = true
}


# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
