#   # 600 -  10 minutes
#   # 630 - 10 minutes and 30 seconds
#   # 900 - 15 minutes
#   # 1200 - 20 minutes
#   # 1230 - 20 minutes and 30 seconds
#   # 1800 - 30 minutes
#   # 3600 - 60 minutes/1 hour

#########################################
# Youinked from a dotfiles repo

$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
  inhibit_sleep = 1
  lock_cmd = $lock_cmd
  before_sleep_cmd = $lock_cmd
  # after_sleep_cmd = hyprctl dispatch dpms on
  ignore_dbus_inhibit = /opt/spotify/spotify
}

listener {
  timeout = 1200
  on-timeout = loginctl lock-session
}

# listener {
#   timeout = 1800
#   on-timeout = hyprctl dispatch dpms off
#   on-resume = hyprctl dispatch dpms on
# }
#
# listener {
#   timeout = 3600
#   on-timeout = $suspend_cmd
#   on-resume = hyprctl dispatch dpms on
# }
