#######################################################
### This entire file is managed entirely by wallust ###
#######################################################

$wallpaper = /home/dwarf/Pictures/wallpapers/wallhaven-vgor6p.jpg

preload = $wallpaper
wallpaper = , contain:$wallpaper
