#### 
# Items starting with 01_init.conf 
# are effectively a 'init.lua' or 'default.nix' or '__init__.py' file
# for the current folder structure.
# 
# Other 'numbered' files are loaded by the 01_init.conf file in that folder,
# or may be required/sourced by files in that folder - 
# 
# They're effectively (variable) dependencies.
#
#########################
$hyprdir = $HOME/.config/hypr
$rules_dir = $hyprdir/configs/rules
$keymaps_dir = $hyprdir/configs/keymaps

source = $hyprdir/configs/programs.conf
#########################


#
# Consider checking out: 
# hyprkcs-git - GUI keyboard binding manager for Hyprland
#
#

#########################
# important
# source = $hyprdir/configs/env.conf # re-enable if NOT using uwsm to manage hyprland launchng

source = $hyprdir/hypr-colors.conf
source = $hyprdir/configs/monitor.conf

#########################

# source = $keymaps_dir/01_init.conf
source = $rules_dir/01_init.conf

#########################

#########
######### Standard Hprland configs
# source = $hyprdir/hypr-source.conf

# source = $hyprdir/configs/execs.conf
source = $hyprdir/configs/visualfeel.conf
source = $hyprdir/configs/input.conf
source = $hyprdir/configs/group.conf
source = $hyprdir/configs/misc.conf

source = $hyprdir/configs/layouts.conf

#########################
#########################

source = $hyprdir/configs/binds.conf
source = $hyprdir/configs/xwayland.conf
source = $hyprdir/configs/opengl.conf

###########################

source = $hyprdir/configs/render.conf
source = $hyprdir/configs/cursor.conf
source = $hyprdir/configs/ecosystem.conf
source = $hyprdir/configs/quirks.conf
source = $hyprdir/configs/debug.conf


source = $hyprdir/configs/monitor.conf

#########
######### DMS configs
# If using this, disable the 'hypr-source.conf' line.
source = $hyprdir/dms/01_init.conf


exec-once = pactl set-sink-mute @DEFAULT_SINK@ 0           # PulseAudio controller - toggles mute on the DEFAULT channel
# Enabled auto mounting of USB devices, -n { notificaitons } -- -t { tray-icon } -- -m { mode for the tray menu }
exec-once = uwsm app -t service -- udiskie -n -t -m flat &

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
