#########################
$hyprdir = $HOME/.config/hypr
$rules_dir = $hyprdir/configs/rules
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
#########################


# exec-once = systemctl disable --now --user hypridle.service
# exec-once = systemctl enable --now --user hypridle.service

# exec-once = systemctl enable --user  dms
# exec-once = systemctl disable --now --user dms

source = $keymaps_dir/01_init.conf
source = $hyprdir/configs/execs.conf

