# source /home/$USER/.cache/wal/colors-hyprland
# source = ./common_vars.conf

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on display
    ignore_dbus_inhibit = /opt/spotify/spotify
}

listener {
    timeout = 900 # 15 minutes
    on-timeout = brightnessctl -s set 10 && notify-send "System" "Screen brightness set to 10% after 15 minutes of inactivity." -i $wallpaper
    on-resume = brightnessctl -r
    # on-timeout = source $colors_file && notify-send "System" "You are about to be locked out!" -i $wallpaper_path
}

# Turn off kbd backlight when we timeout the initial listener
listener {
    timeout = 910 # 15 minutes and 10 seconds
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 && notify-send "System" "Keyboard backlight turned off after 15 minutes of inactivity." -i $wallpaper
    on-resume = brightnessctl -rd rgb:kbd_backlight
    # on-resume = sleep 2 && source $colors_file && notify-send "System" "Unlocked! Hey $USER" -i $wallpaper_path
}

listener {
    timeout = 1200 # 20 minutes
    on-timeout = hyprctl dispatch dpms off && loginctl lock-session # screen off after 20 minutes
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # turn on screen and restore brightness
}

listener {
    timeout = 7200 # 120 minutes / 2 hours
    on-timeout = systemctl suspend # suspend after 2 hours
}
