# Used by:
# hyprland-preview-share-picker-git
# Sets a custom picker binary for the screencopy protocol. This is useful if you want to use a different picker than the default one provided by Hyprland.

screencopy {
    custom_picker_binary = hyprland-preview-share-picker
}

