[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "plugin diff"
desc = "Diff the selected with the hovered file"


[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
