# Disables the 'unsupported flags' notice/warning banner
--test-type
# If running on Wayland (and via Hyprland + HDR)
--disable-features=WaylandWpColorManagerV1
--enable-blink-features=MiddleClickAutoscroll
# --enable-blink-features=MiddleClickAutoscroll
