# Disables the 'unsupported flags' notice/warning banner
--test-type
# Vesktop is good about this, but doesn't hurt to be explicit
# --ozone-platform=wayland
# --ozone-platform=wayland
--enable-features
--lang=en-US
--service-sandbox-type=none
# --use-angle=vulkan
# --use-gl=angle
# Enable middle click autoscroll
--enable-blink-features=MiddleClickAutoscroll
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecoder,AcceleratedVideoEncoder,PdfUseShowSaveFilePicker
# If running on Wayland (and via Hyprland + HDR) - WaylandWpColorManagerV1
--disable-features=HardwareMediaKeyHandling,LocalNetworkAccessChecks,MediaSessionService,ScreenAIOCREnabled,SpareRendererForSitePerProcess,TraceSiteInstanceGetProcessCreation,WinRetrieveSuggestionsOnlyOnDemand,WaylandWpColorManagerV1
--variations-seed-version
--ignore-gpu-blocklist
# below is from issue: https://github.com/Vencord/Vesktop/issues/1207#issue-3661288654
--render-node-override=/dev/dri/renderD128
--enable-crash-reporter=XXXXXXXXXX,no_channel
--user-data-dir=/home/XXXXXX
# --shared-files=v8_context_snapshot_data:100
--field-trial-handle=XXXXXXX
--trace-process-track-uuid=XXXXXXXXXX
