# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

#################
### ECOSYSTEM ###
#################

ecosystem {
    no_update_news = false
    no_donation_nag = true
    enforce_permissions = false
}
