#########################
$hyprdir = $HOME/.config/hypr
source = $hyprdir/configs/programs.conf
#########################

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# exec-once = pypr
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
# exec-once = swww-daemon # animated wallpaper daemon

exec-once = uwsm app -t service -- $notification_daeomon
exec-once = uwsm app -t service -- $wallpaper_daeomon
exec-once = uwsm app -t service -- $notifications

# exec-once = $idle_manager
# exec-once = $clipboard_history --record
# exec-once = wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'
exec-once = uwsm app -- $bar

exec-once = $wallpaper_prog
# exec-once = uwsm app -- signal-desktop --use-tray-icon --enable-features=UseOzonePlatform --ozone-platform=wayland --disable-features=WaylandWpColorManagerV1 -- %u

# exec-once = $notification_daeomon & $notification -df & $bar & $wallpaper_prog &

# Will also want to start the polkit agent -- needed for GUI apps that ask for elevation
# If NOT using uwsm will need: 
# exec-once = systemctl --user start hyprpolkitagent
#
# If using uwsm - turning it on via:
# systemctl --user enable --now hyprpolkitagent.service

# systemctl --user enable --now hyprsunset.service
# exec-once = hyprsunset

# exec-once = $wallpaper_prog &
