# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

####################
### EXPERIMENTAL ###
####################

# Since The release of Mesa 25.1.1 settings below are no longer required, so just skip.
experimental {
    xx_color_management_v4 = true
}
