# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_model =
    kb_layout = us
    kb_variant =
    kb_options = grp:alt_shift_toggle
  # kb_options = fkeys:basic_13-24
    kb_rules =
    kb_file = 

    numlock_by_default = false
    resolve_binds_by_sym = false

    repeat_delay = 160
    repeat_rate = 60
    sensitivity = 0.00

    accel_profile = flat
    force_no_accel = true
    left_handed = false

    scroll_points = 
    scroll_method = 
    scroll_button = 0
    scroll_button_lock = false
    scroll_factor = 1.0
    natural_scroll = false

  # See below re focus
    follow_mouse = 2
    mouse_refocus = true
    follow_mouse_threshold = 0.0
    focus_on_close = 0

  # ------
  # 0 - Cursor movement will not change focus.
  # 1 - Cursor movement will always change focus to the window under the cursor.
  # 2 - Cursor focus will be detached from keyboard focus. Clicking on a window will move keyboard focus to that window.
  # 3 - Cursor focus will be completely separate from keyboard focus. Clicking on a window will not change keyboard focus.

    ## Default: 
    #float_switch_override_focus = 2
    float_switch_override_focus = 0

    special_fallthrough = false
    off_window_axis_events = 1
    emulate_discrete_scroll = 1

    touchpad  {
        disable_while_typing = true
        natural_scroll = true
        scroll_factor = 1.0 
        middle_button_emulation = false
        tap_button_map = 
        clickfinger_behavior = false

        tap-to-click = true                                # Enable tap to click -- May want to remove this though
        drag_lock = 2
        tap-and-drag = true
        flip_x = false 
        flip_y = false
        drag_3fg = 0
    }

    touchdevice {
        enabled = false
        transform = -1
        output = 
    }

    tablet {
        transform = -1
        output = 
        # region_position = [0, 0]
        absolute_region_position = false
        # region_size = [0, 0]
        relative_input = false
        left_handed = false
        # active_area_size = [0, 0]
        # active_area_position = [0, 0]
    }
}


# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    # workspace_swipe = true
    # workspace_swipe_fingers = 3
    # workspace_swipe_min_fingers = 3
    workspace_swipe_distance = 200
    workspace_swipe_touch = false
    workspace_swipe_invert = true
    workspace_swipe_touch_invert = false
    workspace_swipe_min_speed_to_force = 30
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_create_new = true
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10          # in px, the distance to swipe before direction lock activates (touchpad only).
    workspace_swipe_forever = false
    workspace_swipe_use_r = false
}
