# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

#################
### LAYOUT(s) ###
#################

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling bound in ./config/binds
    force_split = 2 # default - 0 |  0 -> split follows mouse, 1 -> always split to the left (new = left or top) 2 -> always split to the right (new = right or bottom)
    preserve_split = true # You probably want this
    smart_split = false
    smart_resizing = true
    special_scale_factor = 0.8
    use_active_for_splits = true
    split_bias = 0
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    orientation = center
    slave_count_for_center_master = false
    mfact = 0.6
    new_on_top = false
    # new_on_active = before
    # always_keep_position = true
    # allow_small_split = true
    # new_status = slave
}
