# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

###############
### OPPENGL ###
###############

opengl {
    nvidia_anti_flicker = true
}
