###################
### MY PROGRAMS ###
###################

$hyprdir = $HOME/.config/hypr

# $old_terminal = wezterm
$terminal = ghostty

# Will want to change this out for Dolphin at some point
$fileManager = thunar
$menu = tofi-drun
$menu_other = wofi -n
$locking = hyprlock
$logout_prog = wleave -f
$browser = zen-browser
$screenshot = $hyprdir/scripts/screenshot.fish
$clipboard_history = clapboard

$notification_daeomon = swaync
$notifications = swaync-client -df
$bar = waybar
$color_picker = hyprpicker -na -f hex


### NOTE ###
#
### UPDATE ENVS IN UWSM ALSO ###
#
# Also update in `../../uwsm/env:62`
#
### UPDATE ENVS IN UWSM ALSO ###
### NOTE ###

# Use waypaper to do basically everything, then callout to --restore for whatever the backend was
#
# $wallpaper_prog = hyprpaper
#
# requires if using mpvpaper -> 'mpv' and 'mpvmpvpaper'
### Currently using swww (as using gifs) converted using ffmpeg
# $wallpaper_prog = waypaper --restore
# env = WALLPAPER_BACKEND,waypaper

$wallpaper_prog = swww --restore
env = WALLPAPER_BACKEND,swww

# If using hyprpaper as the wallpaper manager, will want to enable and start the service
# systemctl --user enable --now hyprpaper
# systemctl --user start --now hyprpaper

# Only required if using swww as the waypaper backend
$wallpaper_daeomon = swww-daemon
# Can only set to startup via systemctl or uwsm

# Run the swww-daemon as a service via a uwsm slice (background compatible when -t service)
# $wallpaper_prog = uwsm app -t service -- swww-daemon

$idle_manager = hypridle
