
quirks {
    # Some clients expect monitor to be in HDR mode prior to the client start.
    # This breaks auto HDR activation and can cause whitescreen and flickering.
    # Use prefer_hdr to fix it,
    #
    # Report HDR mode as preferred. 0 - off, 1 - always, 2 - gamescope only	
    prefer_hdr = 1
}
