# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

##############
### RENDER ###
##############

render {
    # 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
    direct_scanout = 2
    expand_undersized_textures = true
    xp_mode = false
    #2 means “auto” which disables them on Nvidia.
    ctm_animation = 2

    # 0 - off, 1 - always, 2 - hdr only
    cm_fs_passthrough = 1

    # #requires restart
    cm_enabled = true
    # TODO: check against PR: #12127 : "cm:handle CM for SDR content with cm=hdr,cmd_sdr_eotf=2"
    # discussion: #12104 : "HDR unaware applications blow up colors in direct scanout"

    send_content_type = true
    # Auto-switch to HDR in fullscreen when needed. 0 - off, 1 - switch to cm, hdr, 2 - switch to cm, hdredid
    cm_auto_hdr = 2
    new_render_scheduling = false
    non_shader_cm = 1
    # cm_sdr_eotf = 3

    # TEST: toggle these (from whatever the defaults are) and see if 
    # if assists the semi-random freezes (idk what these settings actually do tbf)
    # explicit_sync = 0
    # explicit_sync_kms = 0
}
