# #########################
# $hyprdir = $HOME/.config/hypr
# source = $hyprdir/configs/programs.conf
# #########################

##############
### RENDER ###
##############

render {
    # 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
    direct_scanout = 2
    expand_undersized_textures = true
    xp_mode = false
    #2 means “auto” which disables them on Nvidia.
    ctm_animation = 2

    # 0 - off, 1 - always, 2 - hdr only
    # cm_fs_passthrough = 1

    # #requires restart
    cm_enabled = true
    # TODO: check against PR: #12127 : "cm:handle CM for SDR content with cm=hdr,cmd_sdr_eotf=2"
    # discussion: #12104 : "HDR unaware applications blow up colors in direct scanout"

    send_content_type = true
    # Auto-switch to HDR in fullscreen when needed. 0 - off, 1 - switch to cm, hdr, 2 - switch to cm, hdredid
    cm_auto_hdr = 2
    new_render_scheduling = false
    non_shader_cm = 1
    cm_sdr_eotf = gamma22

    # Enable commit timing proto. Requires restart
    commit_timing_enabled = true

    # Use FP16 buffers internally. 0 - disabled, 1 - enabled, 2 - enabled in hdr mode
    # Default: 2
    use_fp16 = 2

    # Keep umodified SDR frame copy for sreensharing.
    # 0 - disabled,
    # 1 - on,
    # 2 - auto (enabled in HDR with SDR modifiers).
    # Set to 1 if screenshots are transparent.
    keep_unmodified_copy = 2

    # Use experimental blurred bg blending (glitched on rotated screens).
    # Set to true if blur is missing with fp16 or keep_unmodified_copy
    use_shader_blur_blend = true

    # 0 - external ctm is disabled in fullscreen,
    # 1 - external ctm is enabled in fullscreen,
    # 2 - external ctm is disabled for fullscreen photo/video/game content types.
    #
    # 2 is the new default because it doesn't make sense to apply hyprsunset and similar to those content types.
    # EG: setting to 1 would mean something like hyprsunset is ALWAYS on, regardless of fullscreen or not
    non_shader_cm_interop = 2


    # TEST: toggle these (from whatever the defaults are) and see if 
    # if assists the semi-random freezes (idk what these settings actually do tbf)
    # explicit_sync = 0
    # explicit_sync_kms = 0
}
