-- #########################
-- $hyprdir = $HOME/.config/hypr
-- source = $hyprdir/configs/programs.conf
-- #########################

--############
--## BINDS ###
--############

-- Binds
-- https://wiki.hypr.land/Configuring/Variables/#binds
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
  ---@type HL.ConfigOpt.Binds
  binds = {
    pass_mouse_when_bound = false,
    scroll_event_delay = 250,
    workspace_back_and_forth = true,
    hide_special_on_workspace_change = false,
    allow_workspace_cycles = true,
    workspace_center_on = 1, -- 0 is center, 1 is last active window of that workspace
    focus_preferred_method = 0, -- 0 - history, 1 - length
    ignore_group_lock = false,
    movefocus_cycles_fullscreen = false,
    movefocus_cycles_groupfirst = false,
    disable_keybind_grabbing = false, -- if enabled, apps requesting (eg: VM's) won't be able to do so
    window_direction_monitor_fallback = true,
    allow_pin_fullscreen = false,
    drag_threshold = 0,
  },
})
