--############################
--## ENVIRONMENT VARIABLES ###
--############################

--### IF USING uwsm, DON'T LOAD VIA HERE, USE ~/.config/uwsm/

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Toolkit Backend Variables
-- wayland if available, otherwise x11, otherwise fallback to another available backend
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — malformed env on line 60: GDK_BACKEND,wayland,x11
-- use wayland primarily, fallback can also add ;xcb
hl.env("QT_QPA_PLATFORM", "wayland")
--;xcb
-- Set to x11 if games that provider older version of SDL have compat. issues
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")

-- XDG Specifications
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- Qt Variables
-- Removed duplicate
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
-- env = QT_QPA_PLATFORM,wayland;xcb
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
-- can't get qt6ct to work
-- env = QT_QPA_PLATFORMTHEME,qt6ct
-- TODO: manual review — malformed env on line 81: QT_QPA_PLATFORMTHEME=hyprqt6engine

hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")

-- NVIDIA Specific
-- it causes issues like Hyprland crashing so care
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
-- - Controls if G-Sync capable monitors should use Variable Refresh Rate (VRR)
hl.env("__GL_GSYNC_ALLOWED", "1")
-- - Controls if Adaptive Sync should be used. Recommended to set as 0 to avoid having problems with some games
hl.env("__GL_VRR_ALLOWED", "0")

-- Themeing Related Variables
hl.env("GTK_THEME", "Adwaita:dark")

hl.env("HYPRCURSOR_THEME", "Hyprcursor-Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- From other sections of docs

hl.env("WLR_RENDERER_ALLOW_SOFTWARE", "1")
-- Uncommented; enable if needed for NVIDIA
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
hl.env("NVD_BACKEND", "direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- firefox
hl.env("MOZ_ENABLE_WAYLAND", "2")
----------------
