[settings]
mouse_mode = true
data_compact_columns = true
data_row_spacer = false

[keybindings.Menu]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-5>" = "FocusFavorites"

"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Ctrl-m>" = "FocusFavorites"

"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Editor]
"<Ctrl-q>" = "AbortQuery"
"<F5>" = "SubmitEditorQuery"
"<F7>" = "SubmitEditorQueryBypassParser"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-5>" = "FocusFavorites"

"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Ctrl-m>" = "FocusFavorites"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.History]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-5>" = "FocusFavorites"

"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Ctrl-m>" = "FocusFavorites"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Data]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-5>" = "FocusFavorites"

"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Ctrl-m>" = "FocusFavorites"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.Favorites]
"<Ctrl-c>" = "Quit"
"q" = "AbortQuery"
"<Ctrl-1>" = "FocusMenu"
"<Ctrl-2>" = "FocusEditor"
"<Ctrl-3>" = "FocusData"
"<Ctrl-4>" = "FocusHistory"
"<Ctrl-5>" = "FocusFavorites"


"<Ctrl-k>" = "FocusMenu"
"<Ctrl-j>" = "FocusEditor"
"<Ctrl-h>" = "FocusData"
"<Ctrl-g>" = "FocusHistory"
"<Ctrl-m>" = "FocusFavorites"
"<Tab>" = "CycleFocusForwards"
"<Backtab>" = "CycleFocusBackwards"

[keybindings.PopUp]
"<Ctrl-c>" = "Quit"

[db]
sqlite-test = { connection_string = "sqlite://./test.db", driver = "sqlite" }
