return {
  "NvChad/nvim-colorizer.lua",
  -- enabled = false,
  lazy = true,
  ---@type LazyEventSpec
  event = "LspAttach",
  ft = {
    "css",
    "html",
    "javascript",
    "lua",
    "markdown",
    "scss",
    "txt",
    "vim",
    "yaml",
    "json",
    "typescript",
    "typescriptreact",
    "javascriptreact",
    "norg",
    "org",
    "pandoc",
  },
  opts = {
    options = {
      parsers = {
        css = true,
        html = true,
        javascript = true,
        lua = true,
        markdown = true,
        scss = true,
        txt = true,
        vim = true,
        yaml = true,
        json = true,
        typescript = true,
        typescriptreact = true,
        javascriptreact = true,
        norg = true,
        org = true,
        pandoc = true,
      },
    },

    -- user_default_options = {
    -- 	tailwind = "both",
    -- 	css = true,
    -- 	css_fn = true,
    -- 	names = false,
    -- },
  },
}
