#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $keymaps_dir/02_map_mods.conf
#########################


source = ./binds.conf
source = ./colors.conf
source = ./cursor.conf
source = ./cursor.conf
source = ./execs.conf
source = ./layerrules.conf
source = ./layout.conf
source = ./outputs.conf
source = ./windowrules.conf
