#########################
$hyprdir = $HOME/.config/hypr
source = $hyprdir/configs/programs.conf
#########################

exec-once = pactl set-sink-mute @DEFAULT_SINK@ 0           # PulseAudio controller - toggles mute on the DEFAULT channel
exec-once = uwsm app -t service -- udiskie -n -t -m flat &
