#########################
$hyprdir = $HOME/.config/hypr
$keymaps_dir = $hyprdir/configs/keymaps
source = $hyprdir/configs/programs.conf
source = $keymaps_dir/02_map_mods.conf
#########################

# === Application Launchers ===
# Tofi is sooooo much faster
bind = $mainMod, r, exec, $menu

bind = $mainModCtrl, r, exec, dms ipc call spotlight toggle
bind = $mainModCtrl, v, exec, dms ipc call clipboard toggle
bind = $mainModCtrl, m, exec, dms ipc call settings focusOrToggle
bind = $mainModCtrl, a, exec, dms ipc call notifications toggle

bind = $mainModCtrl, w, exec, dms ipc call hypr toggleOverview
bind = $mainModAlt, d, exec, dms ipc call night toggle

bind = $mainMod, y, exec, dms ipc call dankdash wallpaper
bind = $mainMod, m, exec, dms ipc call powermenu toggle
bind = $mainModCtrl, n, exec, dms ipc call notepad toggle

bind = $mainMod, z, exec, dms ipc call dash toggle overview
bind = $mainMod, x, exec, dms ipc call control-center toggle


# === Security ===
bind = $mainMod, u, exec, dms ipc call lock lock

# === Screenshots ===
bind = $mainModCtrl, s, exec, dms screenshot

# === System Controls ===
## Toggles the display, basically a 'sleep' for all screens.
# bind = $mainModShift, p, dpms, toggle

# === Audio Controls ===
bindel = , XF86AudioRaiseVolume, exec, dms ipc call audio increment 3
bindel = , XF86AudioLowerVolume, exec, dms ipc call audio decrement 3

bindl = , XF86AudioMute, exec, dms ipc call audio mute
bindl = , XF86AudioMicMute, exec, dms ipc call audio micmute

bindel = , XF86MonBrightnessUp, exec, dms ipc call brightness increment 5 ""
bindel = , XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5 ""

bindl = , XF86AudioNext, exec, dms ipc call mpris next
bindl = , XF86AudioPrev, exec, dms ipc call mpris previous

bindl = , XF86AudioPause, exec, dms ipc call mpris playPause
bindl = , XF86AudioPlay, exec, dms ipc call mpris playPause

bindel = CTRL, XF86AudioRaiseVolume, exec, dms ipc call mpris increment 3
bindel = CTRL, XF86AudioLowerVolume, exec, dms ipc call mpris decrement 3

# === Brightness Controls ===

##### from orignal config(s)
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


## To prevent duplication, we can source the rem. from vanilla hyprland setup files
source = $keymaps_dir/map_general.conf
source = $keymaps_dir/map_programs.conf
source = $keymaps_dir/map_windows_workspaces.conf
