##################################################
### REMBMER TO INCLUDE!! ###
##################################################
#
#########################
### Get the window via ###
# `"sleep 3; hyprctl activewindow"`
### Paste info at top of file ###
#########################
#


# Tagging
windowrule {
  name = tag-dms-quickshell
  match:class = ^(org.quickshell)$
  tag = +dms-quickshell
}

## Float things
windowrule {
  name = float-tagged-dms-quickshell
  match:tag = dms-quickshell
  float = true
  persistent_size = true
  # center = true
  # size = 1280 720
}

