##################################################
### REMBMER TO INCLUDE!! ###
##################################################
#
#########################
### Get the window via ###
# `"sleep 3; hyprctl activewindow"`
### Paste info at top of file ###
#########################
#


# Tagging
windowrule {
  name = tag-dms-quickshell
  match:class = ^(org.quickshell)$
  tag = +dms-quickshell
}

## Float things
windowrule {
  name = float-tagged-dms-quickshell
  match:tag = dms-quickshell
  float = true
  persistent_size = true
  # center = true
  # size = 1280 720
}


# layerrule = blur on, ignore_alpha 0.5, match:namespace quickshell:overview
layerrule = animation slide right, match:namespace dms:control-center
layerrule = animation slide left, match:namespace dms:dash
layerrule = animation slide top, match:namespace dms:workspace-overview

layerrule = blur on, ignore_alpha 0.3, match:namespace dms:(bar|tooltip|toast|dock-context-menu|tray-menu-window|control-center|notification-center-popout|dash|system-update|process-list-popout|battery|popout|app-launcher)
layerrule = blur on, ignore_alpha 0.2, match:namespace dms:(polkit|notification-center-modal|color-picker|clipboard|spotlight|settings|process-list-modal)

