version = "12"
default_host_triple = "x86_64-unknown-linux-gnu"
default_toolchain = "nightly-x86_64-unknown-linux-gnu"

# default_host_triple = "x86_64-pc-windows-gnu"
# default_toolchain = "nightly-x86_64-pc-windows-gnu"


profile = "complete"

[overrides]
