# Formatting per lang
[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "."] }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} 
auto-format = true

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "py"
args = ["-m", "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "src/main.py"}


[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
# pass format options according to https://github.com/typescript-language-server/typescript-language-server#workspacedidchangeconfiguration omitting the "[language].format." prefix.
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }
