--########################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mods = require("shared.keymaps.mods")

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mods.main_mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mods.main_mod .. " + mouse:273", hl.dsp.window.resize())
