--########################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mods = require("shared.keymaps.mods")
local progs = require("shared.programs")

--########################

hl.bind(mods.with(mods.main_mod, "r"), hl.dsp.exec_cmd(progs.menu))
hl.bind(mods.with(mods.main_mod_shift, "r"), hl.dsp.exec_cmd(progs.menu_other))

hl.bind(mods.with(mods.main_mod, "t"), hl.dsp.exec_cmd(progs.term))
hl.bind(mods.with(mods.main_mod_ctrl, "t"), hl.dsp.exec_cmd(progs.second_term))
hl.bind(mods.with(mods.main_mod_alt, "t"), hl.dsp.exec_cmd("kitty"))

hl.bind(mods.with(mods.main_mod, "b"), hl.dsp.exec_cmd(progs.browser))
hl.bind(mods.with(mods.main_mod_shift, "e"), hl.dsp.exec_cmd(progs.file_manager))
hl.bind(mods.with(mods.main_mod_shift, "c"), hl.dsp.exec_cmd(progs.color_picker))

hl.bind(mods.with(mods.main_mod, "v"), hl.dsp.exec_cmd("hyprvoice toggle"))
