--########################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mods = require("shared.keymaps.mods")

--########################

-- hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("uwsm stop")) -- exit
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("hyprshutdown --vt 2")) -- exit

-- Can define via exec/IPC call (Though this has some performance overhead compared to chaining commands)
-- bind = $mainMod, q, exec, hyprctl dispatch killactive && hyprctl dispatch focusmonitor 0

-- Or can 'chain' shortcuts.

-- TODO: Mmove the quit logic stuff to a function so it's
-- idempotent of the ordering in the file.

hl.bind(mods.with(mods.main_mod, "q"), function()
  hl.dispatch(hl.dsp.window.close())
  hl.dispatch(hl.dsp.focus({ monitor = 0 }))
end)

--### IMPORTANT END ####

hl.bind(mods.with(mods.main_mod, "f"), hl.dsp.window.float({ action = "toggle" }))
hl.bind(mods.with(mods.main_mod, "c"), hl.dsp.window.center())

hl.bind(mods.with(mods.main_mod, "p"), hl.dsp.window.pin())

-- groups
hl.bind(mods.with(mods.main_mod_shift, "g"), hl.dsp.group.lock({ action = "toggle" }))
hl.bind(mods.with(mods.main_mod, "g"), hl.dsp.group.toggle())

hl.bind(mods.with(mods.main_mod, "Home"), hl.dsp.group.prev())
hl.bind(mods.with(mods.main_mod, "End"), hl.dsp.group.next())
hl.bind(mods.with(mods.main_mod, "s"), hl.dsp.window.pseudo())

-- ## TODO: Error'ing
-- bind = $mainMod, Space, togglesplit # dwindle

hl.bind(mods.with(mods.main_mod_shift, "f"), hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mods.with(mods.main_mod_ctrl, "f"), hl.dsp.layout("swapwithmaster master"))
--# ^ Allow swapping when using 'master' layout method

-- this handles for _all_ types of windows:
-- hl.bind(mods.alt_tab, function()
--   hl.dispatch(hl.dsp.window.cycle_next({ next = true }))
--   hl.dispatch(hl.dsp.window.bring_to_top())
-- end)

-- TODO: we need to find a way to mark the original window
-- and ensure we jump back to that specific instance.
-- Currently (for eg: scrolling) - we always
-- return to the first item on the strip, not the original window that was focused.
hl.bind(mods.alt_tab, function()
  -- local cur_window = hl.get_active_window()

  hl.dispatch(hl.dsp.window.cycle_next({
    floating = not hl.get_active_window().floating,
  }))
  -- hl.dispatch(hl.dsp.focus({ window = cur_window, }))
end)
