# On Apple MacBook Pro (Early 2015) with Arch Linux - 
# Use IWD as backend and the Linux-mainline drivers will 
# handle the rest.
#
# wpa_supplicant is not needed and causes more 
# problems than it solves.
#
# [device]
# wifi.backend=iwd
