[user]
name = "MrDwarf7"
email = "129040985+MrDwarf7@users.noreply.github.com"

[colors]
"diff added token" = { bg = "#002200", underline = false } # same color as "green"
"diff removed token" = { bg = "#221111" }                  #, underline = false }

[ui]
default-command = ["log", "--limit", "10"] # disable the message banner
conflict-marker-style = "git"
diff-editor = ":builtin"
diff-formatter = ":color-words"
pager = ":builtin"

[revset-aliases]
H = '@'
