[user]
name = "MrDwarf7"
email = "129040985+MrDwarf7@users.noreply.github.com"

[signing]
behavior = "own"
backend = "gpg"

[git]
auto-local-bookmark = true

[colors]
"diff added token" = { bg = "#002200", underline = false } # same color as "green"
"diff removed token" = { bg = "#221111" }                  #, underline = false }

[ui]
default-command = ["log", "--limit", "10"] # disable the message banner
conflict-marker-style = "git"
diff-editor = ":builtin"
diff-formatter = ":git"
# diff-formatter = ":color-words"
# diff-formatter = [ "delta", "--color-only", "$left", "$right" ] # ":color-words" (default) | ":git" | ":summary" | ":stat" | ":types" | ":name-only" | (some external tool)
pager = ":builtin"

[aliases]
s = ["util", "exec", "--", "bash", "-c", """
jj show -s "$@"
""", ""]
#    ^^
# This last empty string will become "$0" in bash, so your actual arguments
# are all included in "$@" and start at "$1" as expected.


sh = ["util", "exec", "--", "bash", "-c", """
jj show "$@"
""", ""]


as_commits = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """
jj log --no-pager --color=never --template "commit_id" | sed -E -e "s/^(.*\\s+)(\\w?\\d?)?(\\~?\\s+\\(\\w+\\s?\\w+\\))?/\\2\\3/g" -e "s/^([\\│|\\├\\|\\─|\\╯|\\╮])*//g"
""",
  "",
]
