#
[tools]

# Framework(?)/Package Runtimes
# deno = "latest"

# [tools."npm:tailwindcss"]
# version = "latest"
#
# [tools."npm:@tailwindcss/cli"]
# version = "latest"
#
# [tools."npm:@tailwindcss/language-server"]
# version = "latest"

#### This no longer works anyway - prefer simply: `typescript`
# [tools."npm:@typescript/native-preview"]
# version = "latest"


# # vercel-cli
# [tools."npm:vercel"]
# version = "latest"

# turbopack/turborepo
# [tools."npm:turbo"]
# version = "latest"

# [tools."npm:fieldtheory"]
# version = "latest"
# # "npm:fieldtheory" = "1.2.1"

# [tools."npm:@aoagents/ao"]
# version = "latest"

# fieldtheory - cli for pulling X bookmarks locally (ts doesn't support vivaldi, and it's buggy AF)
# [tools."npm:fieldtheory"]
# version = "latest"


####################################################################################################

## Cargo / Cargo install / Cargo binstall / Rust / Rustup Tools


# [tools."cargo:abscissa"]
# version = "latest"

## REST TUI client - superceded by postings, then by resterm (goated!)
# [tools."cargo:atac"]
# version = "latest"


# [tools."cargo:cargo-audit"]
# version = "latest"

# [tools."cargo:cargo-bloat"]
# version = "latest"


# [tools."cargo:cargo-dist"]
# version = "latest"

# [tools."cargo:cargo-expand"]
# version = "latest"


# [tools."cargo:cargo-insta"]
# version = "latest"


# [tools."cargo:cargo-machete"]
# version = "latest"


# [tools."cargo:spider"]
# version = "latest"

#####
# [tools."cargo:dealve-tui"]
# version = "latest"


### I think is abandoned?
# [tools."cargo:https://github.com/sondr3/git-ignore"]
# version = "branch:main"

# [tools."cargo:gumbo"]
# version = "latest"

# [tools."cargo:knope"]
# version = "latest"

# [tools."cargo:loco"]
# version = "latest"

# [tools."cargo:jj-ryu"]
# version = "latest"

# [tools."cargo:gh-stars"]
# version = "latest"


# [settings]
# npm.package_manager = "bun"


# pipx_uvx = true # Prefer to use ux(x) mode instead of pipx

# python.uv_venv_auto = "create|source" # Auto-source (create if missing) .venv when a uv.lock is present
